CONFIG_LPAI_BTSW_ENABLE=y
CONFIG_LPAI_BT_TEST_MENU=y
CONFIG_NANOPB=y
CONFIG_LPAI_BTSW_BTTEST_ENABLE=y
CONFIG_LPAI_BTSW_ENABLE_ISLAND_TEST=n
CONFIG_LPAI_BTSW_ENABLE_GATT_OFFLOAD=n
CONFIG_STATIC_INIT_GNU=y
CONFIG_POSIX_API=y
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP20=y
CONFIG_LPAI_BT_GATT_THROUGHPUT_MENU=y
CONFIG_LPAI_BTSW_ENABLE_GATT_OFFLOAD_GHEADER=y