#pragma once
/** ============================================================================
 * @file
 *
 * @brief Private Framework state for the Attribute Service.
 *
 * @copyright Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 *
 * ===========================================================================*/

/*==============================================================================
  Include Files
  ============================================================================*/

#include <stdbool.h>
#include "sns_attribute_service.h"
#include "sns_isafe_list.h"
#include "sns_osa_lock.h"
#include "sns_sensor_uid.h"
#include "sns_std_sensor.pb.h"
#include "sns_thread_manager.h"

/*==============================================================================
  Forward Declarations
  ============================================================================*/

struct sns_sensor;
struct sns_fw_sensor;
struct sns_sensor_library;
struct sns_fw_request;
struct sns_attribute_info_big;

/*==============================================================================
  Type Definitions
  ============================================================================*/

/**
 * @brief Priority associated with the events generated by or requests sent to 
 * this sensor.
 * 
 */
typedef struct sns_attr_priority
{
  sns_tmgr_task_prio event_priority; /*!< Priority for events generated by the 
                                      *   sensor. 
                                      */
  sns_tmgr_task_prio req_priority;   /*!< Priority for requests sent to the 
                                      *   sensor. 
                                      */
} sns_attr_priority;

/**
 * @brief Sensor-specific attribute information.  This data may only be modified
 * or accessed while holding the sensor_attributes_lock.
 *
 */
typedef struct sns_attribute_info
{
  struct sns_attribute_info_big *attr_info;
  /* The following field values are determined strictly from Sensor-published
   * attributes, and are available to optimization purposes only. */

  bool available;             /*!< Whether the Sensor has yet published that it 
                               *   is available for clients. 
                               */
  bool is_physical_sensor;    /*!< Whether the sensor is a physical sensor; used
                               *   by PWR Manager. 
                               */
  sns_attr_priority priority; /*!< Whether events generated by or requests sent 
                               *   to this Sensor should receive high priority 
                               *   for processing. 
                               */
  bool island_req;            /*!< Whether requests to this sensor outght to be 
                               *   sent in island memory. 
                               */
} sns_attribute_info;

typedef bool (*process_attribute_cb)(void *value, uint32_t value_len,
                                     void *arg);

/*=============================================================================
  Public Function Declarations
  ===========================================================================*/

/**
 * @brief Handle an attribute request sent to some sensor.  Send an attribute 
 * event back to the client.
 *
 * @param[in] sensor  Sensor whose attributes should be sent.
 * @param[in] req     Any additional request configuration; data stream to sent 
 *                    event.
 *
 * @return
 * SNS_RC_SUCCESS On Success.
 *
 */
sns_rc sns_attr_svc_handle_req(struct sns_sensor *sensor,
                               struct sns_fw_request *req);

/**
 * @brief Initialize the attribute service; to be used only by the Service 
 * Manager.
 */
struct sns_fw_attribute_service *sns_attr_svc_init(void);

/**
 * @brief Callback function used in sns_attr_svc_sensor_foreach().
 * 
 * @param[in] attr_info   Pointer the attribut info.
 * @param[in] arg         Pointer to the User-specified argument.
 * 
 * @return 
 *  - User specific return. 
 *
 */
typedef bool (*sns_attr_svc_sensor_foreach_func)(
    struct sns_attribute_info *attr_info, void *arg);

/**
 * @brief For each sensor on the system, call func with arg.  No locks may be
 * acquired within the callback function.
 *
 * @param[in] func Function called for each known Sensor.
 * @param[in] arg  User-specified argument to be used in func callback.
 *
 * @return 
 *  - False if func() returned false for a given sensor input.
 *
 */
bool sns_attr_svc_sensor_foreach(sns_attr_svc_sensor_foreach_func func,
                                 void *arg);

/**
 * @brief Initialize the attribute service state for a particular Sensor.
 *
 * @param[in] sensor Pointer to the sensor.
 *
 * @return
 *  - SNS_RC_SUCCESS On Success.
 *
 */
sns_rc sns_attr_svc_sensor_init(struct sns_fw_sensor *sensor);

/**
 * @brief Deinitialize and free any state created within init_sensor.
 *
 * @param[in] sensor Pointer to the sensor.
 *
 * @return
 *  - None.
 *
 */
void sns_attr_svc_sensor_deinit(struct sns_fw_sensor *sensor);

/**
 * @brief Look-up and return the Sensors selected resolution.
 *
 * @param[in] attr_info Pointer to the attribute info.
 *
 * @return
 *  - float Return the selected resolution.
 *
 */
float sns_attr_info_get_selected_resolution(
    struct sns_attribute_info const *attr_info);

/**
 * @brief Look-up and return the Sensors selected range.
 *
 * @param[in] attr_info Pointer to the attribute info.
 *
 * @return
 *  - float Return the selected range.
 *
 */
float sns_attr_info_get_selected_range(
    struct sns_attribute_info const *attr_info);

/**
 * @brief Look-up and return the Sensors selected rigidbody.
 *
 * @param[in] attr_info Pointer to the attribute info.
 *
 * @return
 *  -  sns_std_sensor_rigid_body_type Rigid body type.
 */
sns_std_sensor_rigid_body_type
sns_attr_info_get_rigid_body(struct sns_attribute_info const *attr_info);

/**
 * @brief Look-up and return the Sensors stream type.
 *
 * @param[in] attr_info Pointer to the attribute info.
 *
 * @return
 *  - sns_std_sensor_stream_type Stream type.
 * 
 */
sns_std_sensor_stream_type
sns_attr_info_get_stream_type(struct sns_attribute_info const *attr_info);

/**
 * @brief Look-up and return the Sensor vendor string.  As long as vendor_len > 0,
 * vendor will always be null-terminated.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 * @param[out] vendor     Pointer to the vendor name.
 * @param[in]  vendor_len Length of the vendor name.
 *
 * @return 
 *  - None.
 *
 */
void sns_attr_info_get_vendor(struct sns_attribute_info const *attr_info,
                              char *vendor, uint32_t vendor_len);

/**
 * @brief Look-up and return the Sensor data type string.  As long as
 * data_type_len > 0, data_type will always be null-terminated.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 * @param[in]  data_type  Pointer to the data type.
 * @param[in]  attr_info  Length of the data type.
 *
 * @return
 *  - None.
 *
 */
void sns_attr_info_get_data_type(struct sns_attribute_info const *attr_info,
                                 char *data_type, uint32_t data_type_len);

/**
 * @brief Lookup and return the sensor priority flag.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 *
 * @return
 *  - sns_attr_priority Get priority.
 *
 */
sns_attr_priority
sns_attr_info_get_priority(struct sns_attribute_info const *attr_info);

/**
 * @brief Lookup and return the sensor available flag.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 *
 * @return 
 *  - True  If sensor available.
 *  - False Otherwise.
 *
 */
bool sns_attr_info_get_available(struct sns_attribute_info const *attr_info);

/**
 * @brief Set the sensor available flag.  This will allow/prohibit access to this
 * senosr via data streams.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 * @param[in]  available  To set sensor availability.
 *
 * @return
 *  - None.
 *
 */
void sns_attr_info_set_available(sns_attribute_info *attr_info, bool available);

/**
 * @brief Lookup and return whether this is a physical sensor.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 *
 * @return 
 *  - True  If its a physical sensor.
 *  - False Otherwise.
 *
 */
bool sns_attr_info_get_is_physical_sensor(
    struct sns_attribute_info const *attr_info);

/**
 * @brief Lookup and return the Sensor UID.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 *
 * @return
 *  - sns_sensor_uid Sensor SUID.
 *
 */
sns_sensor_uid
sns_attr_info_get_suid(struct sns_attribute_info const *attr_info);

/**
 * @brief Set the Sensor UID associated with this attribute information.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 *
 * @return
 *  - None.
 *
 */
void sns_attr_info_set_suid(struct sns_attribute_info *attr_info,
                            sns_sensor_uid const *suid);

/**
 * @brief Set the vendor associated with this attribute information.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 * @param[in]  vendor     Pointer to the vendor name.
 *
 * @return
 *  - None.
 *
 */
void sns_attr_info_set_vendor(struct sns_attribute_info *attr_info,
                              char const *vendor);

/**
 * @brief Lookup and return the event size associated with this attribute.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 *
 * @return
 *  - int32_t Event size.
 *
 */
int32_t
sns_attr_info_get_event_size(struct sns_attribute_info const *attr_info);

/**
 * @brief Lookup and return the sensor associated with these attributes.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 *
 * @return
 *  - sns_fw_sensor* Sensor pointer.
 *
 */
struct sns_fw_sensor *
sns_attr_info_get_sensor(struct sns_attribute_info const *attr_info);

/**
 * @brief Lookup and return the sensor associated with these attributes.
 * 
 * @param[in]  attr_info  Pointer to the attribute info.
 *
 * @return
 *  - sns_sensor_library* Sensor Library.
 *
 */
struct sns_sensor_library *
sns_attr_info_get_library(struct sns_attribute_info const *attr_info);

/**
 * @brief Get value of island_req flag from the sns_attribute_info.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 *
 * @return
 *  - bool Return the island sensor_req flag.
 *
 */
bool sns_attr_info_get_island_req(struct sns_attribute_info const *attr_info);

/**
 * @brief Get value of is_default flag from the sns_attribute_info.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 *
 * @return
 *  - bool Return is_default flag.
 * 
 */
bool sns_attr_info_get_default(struct sns_attribute_info const *attr_info);

/**
 * @brief Set value of is_default flag from the sns_attribute_info.
 *
 * @param[in]  attr_info  Pointer to the attribute info.
 * @param[in]  val        Value to set in is default flag.
 *
 * @return
 *  - None.
 * 
 */
void sns_attr_info_set_default(struct sns_attribute_info *attr_info, bool val);

/**
 * @brief Lookup given attribute_id and call the process_attribute_cb with the
 * encoded attribute value.
 *
 * @note No mutexes may be acquired within the callback function.
 *
 * @param[in]  attr_info     Pointer to the attribute info.
 * @param[in]  attribute_id  Attribute ID.
 * @param[in]  cb            Process attribute callback function.
 * @param[in]  cb_arg        Pointer to the callback function argument.
 *
 * @return
 *  - True  If successfully process the attribute.
 *  - False Otherwise.
 *
 */
bool sns_attr_info_process_attribute(struct sns_attribute_info *attr_info,
                                     uint32_t attribute_id,
                                     process_attribute_cb cb, void *cb_arg);

/**
 * @brief This function compares suid to internal sensor suid.
 *
 * @param[in] suid  Pointer to SUID.
 *
 * @return 
 *  - True if matches to any of internal sensor suid.
 *  - False otherwise.
 *
 */
bool sns_attr_check_internal_sensor_suid(sns_sensor_uid *suid);

/**
 * @brief This function compares suid and returns attr_info pointer.
 *
 * @param[in] suid  Pointer to SUID.
 *
 * @return 
 *  - sns_attribute_info Pointer to the sensor of specified suid.
 *
 */
sns_attribute_info const *sns_attr_svc_get_attr_from_suid(sns_sensor_uid *suid);
