#pragma once
/** ============================================================================
 * @file
 *
 * @brief An output generated by a Sensor.  The Event may contain multiple
 * logical sensor samples.  The Framework will ensure samples can be
 * fed into the client individually.
 *
 * @copyright  Copyright (c) 2016-2019 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 *
 * ===========================================================================*/

/*==============================================================================
  Include Files
  ============================================================================*/

#include <inttypes.h>
#include "sns_time.h"

/*==============================================================================
  Type Definitions
  ============================================================================*/

/**
 * @brief Represents a sensor event within the Framework.
 * 
 * @note Unlike the other data structures in this directory, this structure
 * cannot be freely casted to/from sns_sensor_event.
 *
 */
typedef struct sns_fw_sensor_event
{
  struct
  {
#ifdef SNS_DEBUG_EVENT_SERVICE
    uint32_t headcode;      /*!< Headcode for debugging purposes. 
                             *   SNS_DEBUG_EVENT_SERVICE Need to be define
                             */
    intptr_t caller;        /*!< Caller information for debugging purposes. */
#endif
    int16_t client_cnt;     /*!< Number of remaining clients to process this 
                             *   event. Set to -1 after sns_event_service_api::
                             *   alloc_event.
                             */
    uint16_t fw_event_len;  /*!< Length of the firmware event. */
  } header;
  sns_sensor_event event;   /*!< Actual sensor event data. */
} sns_fw_sensor_event;  
