#pragma once
/** ============================================================================
 * @file
 *
 * @brief Log packets generated by the Framework.
 *
 * @copyright Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * All rights reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 *
 * ===========================================================================*/

/*==============================================================================
  Include Files
  ============================================================================*/

#include "sns_diag_service.h"
#include "sns_fw_sensor.h"
#include "sns_fw_sensor_instance.h"
#include "sns_rc.h"
#include "sns_request.h"
#include "sns_sensor.h"
#include "sns_sensor_event.h"
#include "sns_sensor_instance.h"
#include "sns_sensor_uid.h"
#include "sns_time.h"
#include "stddef.h"
#include "stdint.h"

/*==============================================================================
  Forward Declarations
  ============================================================================*/

struct sns_fw_sensor_instance;
struct sns_sensor;
struct sns_sensor_instance;
struct sns_sensor_uid;
struct sns_fw_request;
struct sns_sensor_event;
struct sns_fw_data_stream;

/*==============================================================================
  Public Function Declarations
  ============================================================================*/

/**
 * @brief Publish a Sensor Instance API Event Log Packet.
 *
 * @param[in] instance   Sensor Instance generating the event.
 * @param[in] sensor_uid UID of the sensor which received the request.
 * @param[in] event      Event payload.
 *
 * @return
 *  - SNS_RC_SUCCESS        Log is succesfully published.
 *  - SNS_RC_FAILED         Log creation / submission fails.
 *  - SNS_RC_NOT_SUPPORTED  Logging is disabled.
 *
 */
sns_rc sns_fw_log_sensor_inst_api_event(struct sns_sensor_instance *instance,
                                        struct sns_sensor_uid const *sensor_uid,
                                        struct sns_sensor_event *event);

/**
 * @brief Publish a Sensor API Request Log Packet.
 *
 * @param[in] sensor  Sensor servicing the request.
 * @param[in] req     Request payload.
 *
 * @return
 *  - SNS_RC_SUCCESS        Log is succesfully published.
 *  - SNS_RC_FAILED         Log creation / submission fails.
 *  - SNS_RC_NOT_SUPPORTED  Logging is disabled.
 *
 */
sns_rc sns_fw_log_sensor_api_req(struct sns_sensor *sensor,
                                 struct sns_fw_request const *req);

/**
 * @brief Publish a Sensor API Event Log Packet.
 *
 * @param[in] stream  Data Stream on which event is generated.
 * @param[in] event   Event payload.
 *
 * @return
 *  - SNS_RC_SUCCESS        Log is succesfully published.
 *  - SNS_RC_FAILED         Log creation / submission fails.
 *  - SNS_RC_NOT_SUPPORTED  Logging is disabled.
 *
 */
sns_rc sns_fw_log_sensor_api_event(struct sns_fw_data_stream *stream,
                                   struct sns_sensor_event *event);

/**
 * @brief Publish a Client API Request Log Packet.
 *
 * @param[in] instance           Client manager sensor Instance receiving the
 *                               request.
 * @param[in] sensor_uid         ID of the Client Manager sensor generating the
 *                               log.
 * @param[in] log_id             Diag Log ID
 * @param[in] client_connect_id  ID of the connection from whom request is
 *                               received.
 * @param[in] diag_config_ptr    Source sensor diag configuration for logging.
 * @param[in] payload            PB encoded payload of type
 *                               sns_client_request_msg as defined in
 *                               sns_client.proto.
 * @param[in] payload_len        length of the encoded payload.
 *
 * @return
 *  - SNS_RC_SUCCESS        Log is succesfully published.
 *  - SNS_RC_FAILED         Log creation / submission fails.
 *  - SNS_RC_NOT_SUPPORTED  Logging is disabled.
 *
 */

sns_rc sns_fw_log_client_api_msg(intptr_t instance,
                                 sns_sensor_uid const *sensor_uid,
                                 sns_fw_diag_service_log_id log_id,
                                 uint64_t client_connect_id,
                                 sns_diag_datatype_config *diag_config_ptr,
                                 void const *payload, size_t payload_len);

/**
 * @brief Publish a Client API Request Log Packet.
 *
 * @param[in] instance           Client manager sensor Instance receiving the
 *                               request.
 * @param[in] diag_config_ptr    Source sensor diag configuration for logging.
 * @param[in] sensor_uid         ID of the Client Manager sensor generating the
 *                               log.
 * @param[in] client_connect_id  ID of the connection from whom request is
 *                               received.
 * @param[in] payload            PB encoded payload of type
 *                               sns_client_request_msg as defined in
 *                               sns_client.proto.
 * @param[in] payload_len        length of the encoded payload.
 *
 * @return
 *  - SNS_RC_SUCCESS        Log is succesfully published.
 *  - SNS_RC_FAILED         Log creation / submission fails.
 *  - SNS_RC_NOT_SUPPORTED  Logging is disabled.
 *
 */
sns_rc sns_fw_log_client_api_req(struct sns_sensor_instance *instance,
                                 sns_diag_datatype_config *diag_config_ptr,
                                 struct sns_sensor_uid const *sensor_uid,
                                 uint64_t client_connect_id, void *payload,
                                 size_t payload_len);

/**
 * @brief Publish a Client API Response Log Packet.
 *
 * @param[in] instance            Client manager sensor Instance sending the
 *                                response.
 * @param[in] diag_config_ptr     Source sensor diag configuration for logging.
 * @param[in] sensor_uid          ID of the Client Manager sensor generating
 *                                the log.
 * @param[in] client_connect_id   ID of the connection to which response is
 *                                being sent.
 * @param[in] error               The response error.
 *
 * @return
 *  - SNS_RC_SUCCESS         Log is succesfully published.
 *  - SNS_RC_FAILED          Log creation / submission fails.
 *  - SNS_RC_NOT_SUPPORTED   Logging is disabled.
 *
 */
sns_rc sns_fw_log_client_api_resp(struct sns_sensor_instance *instance,
                                  sns_diag_datatype_config *diag_config_ptr,
                                  struct sns_sensor_uid const *sensor_uid,
                                  uint64_t client_connect_id, uint64_t error);

/**
 * @brief Publish a Client API Indication Log Packet.
 *
 * @param[in] instance            Client manager sensor Instance sending the
 *                                indication.
 * @param[in] diag_config_ptr     Source sensor diag configuration for logging.
 * @param[in] sensor_uid          ID of the Client Manager sensor generating
 *                                the log.
 * @param[in] client_connect_id   ID of the connection to which indication is
 *                                being sent.
 * @param[in] payload             PB encoded payload of type
 *                                sns_client_event_msg as defined in
 *                                sns_client.proto.
 * @param[in] payload_len         length of the encoded payload.
 *
 * @return
 *  - SNS_RC_SUCCESS        Log is succesfully published.
 *  - SNS_RC_FAILED         Log creation / submission fails.
 *  - SNS_RC_NOT_SUPPORTED  Logging is disabled.
 *
 */
sns_rc sns_fw_log_client_api_ind(struct sns_sensor_instance *instance,
                                 sns_diag_datatype_config *diag_config_ptr,
                                 struct sns_sensor_uid const *sensor_uid,
                                 uint64_t client_connect_id, void *payload,
                                 size_t payload_len);

/**
 * @brief Publish a Sensor Instance Map Log Packet.
 *
 * @param[in] instance Pointer to the instance of the sensor.
 *
 * @return
 *  - SNS_RC_SUCCESS        Log is succesfully published.
 *  - SNS_RC_FAILED         Log creation / submission fails.
 *  - SNS_RC_NOT_SUPPORTED  Logging is disabled.
 *
 */
sns_rc sns_fw_log_inst_map(struct sns_sensor_instance *instance);
