#ifndef __CLOCKIDPAKALA_H__
#define __CLOCKIDPAKALA_H__

#define BI_TCXO_GATED_FOR_GX_ID                            0xE1229494
#define BI_TCXO_MX_ID                                      0xE0E9F1C0
#define CAM_BIST_MCLK_CC_DEBUG_CLK_ID                      0xC4839D47
#define CAM_BIST_MCLK_CC_DEBUG_DIV_CLK_SRC_ID              0x8F4AFE55
#define CAM_BIST_MCLK_CC_DEBUG_MUX_ID                      0x6632DA35
#define CAM_BIST_MCLK_CC_MCLK0_CLK_ID                      0x9EBD4707
#define CAM_BIST_MCLK_CC_MCLK1_CLK_ID                      0x3993B9D9
#define CAM_BIST_MCLK_CC_MCLK2_CLK_ID                      0x53D01D55
#define CAM_BIST_MCLK_CC_MCLK3_CLK_ID                      0x4632136F
#define CAM_BIST_MCLK_CC_MCLK4_CLK_ID                      0x9E942549
#define CAM_BIST_MCLK_CC_MCLK5_CLK_ID                      0x6DB3DFCA
#define CAM_BIST_MCLK_CC_MCLK6_CLK_ID                      0xA882724F
#define CAM_BIST_MCLK_CC_MCLK7_CLK_ID                      0xDE5D1D64
#define CAM_BIST_MCLK_CC_PLL0_ID                           0x720CA04A
#define CAM_BIST_MCLK_CC_PLL_TEST_CLK_ID                   0x4448D7AA
#define CAM_BIST_MCLK_CC_PLL_TEST_DIV_CLK_SRC_ID           0x26505B18
#define CAM_BIST_MCLK_CC_SLEEP_CLK_ID                      0x601E9655
#define CAM_CC_CAM_TOP_AHB_CLK_ID                          0xFB6EFFD3
#define CAM_CC_CAM_TOP_FAST_AHB_CLK_ID                     0x6660DFFC
#define CAM_CC_CAMNOC_DCD_XO_CLK_ID                        0xD2B89C42
#define CAM_CC_CAMNOC_NRT_AXI_CLK_ID                       0x1372F670
#define CAM_CC_CAMNOC_NRT_CRE_CLK_ID                       0x0D026FA9
#define CAM_CC_CAMNOC_NRT_IPE_NPS_CLK_ID                   0xF47C9124
#define CAM_CC_CAMNOC_NRT_OFE_ANCHOR_CLK_ID                0x449740DB
#define CAM_CC_CAMNOC_NRT_OFE_HDR_CLK_ID                   0x69CE5B39
#define CAM_CC_CAMNOC_NRT_OFE_MAIN_CLK_ID                  0x68D9BDD9
#define CAM_CC_CAMNOC_RT_AXI_CLK_ID                        0x4579B9A5
#define CAM_CC_CAMNOC_RT_IFE_LITE_CLK_ID                   0xEBE41EB5
#define CAM_CC_CAMNOC_RT_TFE_0_BAYER_CLK_ID                0x9CE9F65F
#define CAM_CC_CAMNOC_RT_TFE_0_MAIN_CLK_ID                 0x6D8CFFFB
#define CAM_CC_CAMNOC_RT_TFE_1_BAYER_CLK_ID                0xC97EE881
#define CAM_CC_CAMNOC_RT_TFE_1_MAIN_CLK_ID                 0x9D039983
#define CAM_CC_CAMNOC_RT_TFE_2_BAYER_CLK_ID                0x4F7A1DC9
#define CAM_CC_CAMNOC_RT_TFE_2_MAIN_CLK_ID                 0xC128B6EC
#define CAM_CC_CAMNOC_XO_CLK_ID                            0x6D33216F
#define CAM_CC_CCI_0_CLK_ID                                0x2F0FA585
#define CAM_CC_CCI_1_CLK_ID                                0x0072D990
#define CAM_CC_CCI_2_CLK_ID                                0x68C6ABCF
#define CAM_CC_CORE_AHB_CLK_ID                             0xA974C223
#define CAM_CC_CRE_AHB_CLK_ID                              0x75FFE457
#define CAM_CC_CRE_CLK_ID                                  0x4B3A4DAF
#define CAM_CC_CSI0PHYTIMER_CLK_ID                         0xDF3E55F8
#define CAM_CC_CSI1PHYTIMER_CLK_ID                         0xBD91807B
#define CAM_CC_CSI2PHYTIMER_CLK_ID                         0x411BC4E9
#define CAM_CC_CSI3PHYTIMER_CLK_ID                         0xD8F7C361
#define CAM_CC_CSI4PHYTIMER_CLK_ID                         0xB18687E2
#define CAM_CC_CSI5PHYTIMER_CLK_ID                         0xB51B47B8
#define CAM_CC_CSID_CLK_ID                                 0x81ECCAD5
#define CAM_CC_CSID_CSIPHY_RX_CLK_ID                       0x2FBDAC2F
#define CAM_CC_CSIPHY0_CLK_ID                              0x5BD9C966
#define CAM_CC_CSIPHY1_CLK_ID                              0xD1C62B7E
#define CAM_CC_CSIPHY2_CLK_ID                              0xFB341D3F
#define CAM_CC_CSIPHY3_CLK_ID                              0x29439ED4
#define CAM_CC_CSIPHY4_CLK_ID                              0xDB01488B
#define CAM_CC_CSIPHY5_CLK_ID                              0x482323FC
#define CAM_CC_DEBUG_CLK_ID                                0x8E6D4CE1
#define CAM_CC_DEBUG_DIV_CLK_SRC_ID                        0x44FEDC59
#define CAM_CC_DEBUG_MUX_ID                                0xCEB85AEC
#define CAM_CC_DRV_AHB_CLK_ID                              0x3A323E85
#define CAM_CC_DRV_XO_CLK_ID                               0xD5FFFDE7
#define CAM_CC_GDSC_CLK_ID                                 0xC9FEBE6E
#define CAM_CC_ICP_0_AHB_CLK_ID                            0x7211D0E9
#define CAM_CC_ICP_0_CLK_ID                                0x0BB24F85
#define CAM_CC_ICP_1_AHB_CLK_ID                            0x310B10EC
#define CAM_CC_ICP_1_CLK_ID                                0x6304C346
#define CAM_CC_IFE_LITE_AHB_CLK_ID                         0x27E3565D
#define CAM_CC_IFE_LITE_CLK_ID                             0xD0972606
#define CAM_CC_IFE_LITE_CPHY_RX_CLK_ID                     0x51577E4F
#define CAM_CC_IFE_LITE_CSID_CLK_ID                        0xC6E06EE3
#define CAM_CC_IPE_0_GDSC_ID                               0x5AAE87F4
#define CAM_CC_IPE_NPS_AHB_CLK_ID                          0x52744D44
#define CAM_CC_IPE_NPS_CLK_ID                              0xCF45C1D6
#define CAM_CC_IPE_NPS_FAST_AHB_CLK_ID                     0xD108DD15
#define CAM_CC_IPE_NPS_SPDM_CLK_ID                         0x6C977EB2
#define CAM_CC_IPE_NPS_SPDM_DIV_CLK_SRC_ID                 0xE0D4FE63
#define CAM_CC_IPE_PPS_CLK_ID                              0xFC442BC4
#define CAM_CC_IPE_PPS_FAST_AHB_CLK_ID                     0x45B7C8D8
#define CAM_CC_JPEG_0_CLK_ID                               0x0D313EDB
#define CAM_CC_JPEG_1_CLK_ID                               0xDEA82AA4
#define CAM_CC_JPEG_SPDM_CLK_ID                            0x0CBA0835
#define CAM_CC_JPEG_SPDM_DIV_CLK_SRC_ID                    0xEA3CFA61
#define CAM_CC_OFE_AHB_CLK_ID                              0xDEBB933A
#define CAM_CC_OFE_ANCHOR_CLK_ID                           0x45EE5A6F
#define CAM_CC_OFE_ANCHOR_FAST_AHB_CLK_ID                  0x2D461E24
#define CAM_CC_OFE_GDSC_ID                                 0x8FA54655
#define CAM_CC_OFE_HDR_CLK_ID                              0xB15FF8AD
#define CAM_CC_OFE_HDR_FAST_AHB_CLK_ID                     0x444D474B
#define CAM_CC_OFE_MAIN_CLK_ID                             0x5A5D3019
#define CAM_CC_OFE_MAIN_FAST_AHB_CLK_ID                    0x0EC22040
#define CAM_CC_OFE_SPDM_CLK_ID                             0xD30D7D8D
#define CAM_CC_OFE_SPDM_DIV_CLK_SRC_ID                     0x1E3C1DE8
#define CAM_CC_PLL0_ID                                     0x3E90B842
#define CAM_CC_PLL1_ID                                     0x6237E726
#define CAM_CC_PLL2_ID                                     0x6DF55C3B
#define CAM_CC_PLL3_ID                                     0x9447D816
#define CAM_CC_PLL4_ID                                     0x70B3A5DD
#define CAM_CC_PLL5_ID                                     0x838225F9
#define CAM_CC_PLL6_ID                                     0xC75C6E13
#define CAM_CC_PLL_TEST_CLK_ID                             0x519E3D27
#define CAM_CC_PLL_TEST_DIV_CLK_SRC_ID                     0x2937C1CD
#define CAM_CC_QDSS_DEBUG_CLK_ID                           0x1843A6D1
#define CAM_CC_QDSS_DEBUG_XO_CLK_ID                        0xFC7EF9CE
#define CAM_CC_SLEEP_CLK_ID                                0xCFDF030C
#define CAM_CC_TFE_0_BAYER_CLK_ID                          0x9472AC23
#define CAM_CC_TFE_0_BAYER_FAST_AHB_CLK_ID                 0x476BE85E
#define CAM_CC_TFE_0_GDSC_ID                               0x25AF4AB4
#define CAM_CC_TFE_0_MAIN_CLK_ID                           0x93830ADD
#define CAM_CC_TFE_0_MAIN_FAST_AHB_CLK_ID                  0x07590D19
#define CAM_CC_TFE_0_SPDM_CLK_ID                           0x38FEAFC3
#define CAM_CC_TFE_0_SPDM_DIV_CLK_SRC_ID                   0x435BE60D
#define CAM_CC_TFE_1_BAYER_CLK_ID                          0xD2DDC177
#define CAM_CC_TFE_1_BAYER_FAST_AHB_CLK_ID                 0x7F2A6A05
#define CAM_CC_TFE_1_GDSC_ID                               0xDACB2D75
#define CAM_CC_TFE_1_MAIN_CLK_ID                           0x7A6F433B
#define CAM_CC_TFE_1_MAIN_FAST_AHB_CLK_ID                  0x521D62CF
#define CAM_CC_TFE_1_SPDM_CLK_ID                           0x03F9F48F
#define CAM_CC_TFE_1_SPDM_DIV_CLK_SRC_ID                   0xBFAF486D
#define CAM_CC_TFE_2_BAYER_CLK_ID                          0xEB1B3636
#define CAM_CC_TFE_2_BAYER_FAST_AHB_CLK_ID                 0x14AD9A81
#define CAM_CC_TFE_2_GDSC_ID                               0x0002254C
#define CAM_CC_TFE_2_MAIN_CLK_ID                           0x018B2E20
#define CAM_CC_TFE_2_MAIN_FAST_AHB_CLK_ID                  0x6686474E
#define CAM_CC_TFE_2_SPDM_CLK_ID                           0xBABA923A
#define CAM_CC_TFE_2_SPDM_DIV_CLK_SRC_ID                   0x78B51A05
#define CAM_CC_TITAN_TOP_GDSC_ID                           0x16E83103
#define DISP_CC_DEBUG_CLK_ID                               0x17181EB2
#define DISP_CC_DEBUG_DIV_CLK_SRC_ID                       0x62B24CF1
#define DISP_CC_DEBUG_MUX_ID                               0x3E02FDA9
#define DISP_CC_ESYNC0_CLK_ID                              0xC4F71910
#define DISP_CC_ESYNC1_CLK_ID                              0x9D1CEE3C
#define DISP_CC_MDSS_ACCU_SHIFT_CLK_ID                     0xE9110F99
#define DISP_CC_MDSS_AHB1_CLK_ID                           0xBD9DA764
#define DISP_CC_MDSS_AHB_CLK_ID                            0xD86CF434
#define DISP_CC_MDSS_BYTE0_CLK_ID                          0x62A800C1
#define DISP_CC_MDSS_BYTE0_DIV_CLK_SRC_ID                  0x7355820C
#define DISP_CC_MDSS_BYTE0_INTF_CLK_ID                     0xEC7D494E
#define DISP_CC_MDSS_BYTE1_CLK_ID                          0x0DE1DE46
#define DISP_CC_MDSS_BYTE1_DIV_CLK_SRC_ID                  0x5AC99929
#define DISP_CC_MDSS_BYTE1_INTF_CLK_ID                     0xFEEDA5FA
#define DISP_CC_MDSS_CORE_GDSC_ID                          0x32294237
#define DISP_CC_MDSS_CORE_INT2_GDSC_ID                     0x4A7593B6
#define DISP_CC_MDSS_DPTX0_AUX_CLK_ID                      0xC2E18940
#define DISP_CC_MDSS_DPTX0_CRYPTO_CLK_ID                   0xC95B6162
#define DISP_CC_MDSS_DPTX0_CRYPTO_DIV_CLK_SRC_ID           0x24B06A04
#define DISP_CC_MDSS_DPTX0_LINK_CLK_ID                     0x15BD0141
#define DISP_CC_MDSS_DPTX0_LINK_DIV_CLK_SRC_ID             0x44E0BEA7
#define DISP_CC_MDSS_DPTX0_LINK_INTF_CLK_ID                0xEBAC4D27
#define DISP_CC_MDSS_DPTX0_PIXEL0_CLK_ID                   0x92F8B42B
#define DISP_CC_MDSS_DPTX0_PIXEL1_CLK_ID                   0x5908B325
#define DISP_CC_MDSS_DPTX0_USB_ROUTER_LINK_INTF_CLK_ID     0xDFF7A70E
#define DISP_CC_MDSS_DPTX1_AUX_CLK_ID                      0xA4C9FCBA
#define DISP_CC_MDSS_DPTX1_CRYPTO_CLK_ID                   0xDC4577D5
#define DISP_CC_MDSS_DPTX1_CRYPTO_DIV_CLK_SRC_ID           0xE2B9610C
#define DISP_CC_MDSS_DPTX1_LINK_CLK_ID                     0xA6B8960A
#define DISP_CC_MDSS_DPTX1_LINK_DIV_CLK_SRC_ID             0x0D3EFA4E
#define DISP_CC_MDSS_DPTX1_LINK_INTF_CLK_ID                0xE09D4224
#define DISP_CC_MDSS_DPTX1_PIXEL0_CLK_ID                   0xECF3AF7D
#define DISP_CC_MDSS_DPTX1_PIXEL1_CLK_ID                   0x715982F2
#define DISP_CC_MDSS_DPTX1_USB_ROUTER_LINK_INTF_CLK_ID     0xB01596F5
#define DISP_CC_MDSS_DPTX2_AUX_CLK_ID                      0xEE4EC3B3
#define DISP_CC_MDSS_DPTX2_CRYPTO_CLK_ID                   0xD3922A9C
#define DISP_CC_MDSS_DPTX2_CRYPTO_DIV_CLK_SRC_ID           0x3A8BA1E4
#define DISP_CC_MDSS_DPTX2_LINK_CLK_ID                     0x98555F85
#define DISP_CC_MDSS_DPTX2_LINK_DIV_CLK_SRC_ID             0x430EBF82
#define DISP_CC_MDSS_DPTX2_LINK_INTF_CLK_ID                0xB5F9954A
#define DISP_CC_MDSS_DPTX2_PIXEL0_CLK_ID                   0x2A4E6380
#define DISP_CC_MDSS_DPTX2_PIXEL1_CLK_ID                   0xBABE80B9
#define DISP_CC_MDSS_DPTX3_AUX_CLK_ID                      0xB5F17EF7
#define DISP_CC_MDSS_DPTX3_CRYPTO_CLK_ID                   0x9E1CCAE7
#define DISP_CC_MDSS_DPTX3_CRYPTO_DIV_CLK_SRC_ID           0xFC9F97BB
#define DISP_CC_MDSS_DPTX3_LINK_CLK_ID                     0xCE228C2D
#define DISP_CC_MDSS_DPTX3_LINK_DIV_CLK_SRC_ID             0x15644C83
#define DISP_CC_MDSS_DPTX3_LINK_INTF_CLK_ID                0xCEC7F620
#define DISP_CC_MDSS_DPTX3_PIXEL0_CLK_ID                   0x153148BC
#define DISP_CC_MDSS_ESC0_CLK_ID                           0x4485FD1B
#define DISP_CC_MDSS_ESC1_CLK_ID                           0x27702EBC
#define DISP_CC_MDSS_MDP1_CLK_ID                           0x085D62A2
#define DISP_CC_MDSS_MDP_CLK_ID                            0x6A10EA96
#define DISP_CC_MDSS_MDP_LUT1_CLK_ID                       0x70F2ED4E
#define DISP_CC_MDSS_MDP_LUT_CLK_ID                        0xF02E7C9A
#define DISP_CC_MDSS_NON_GDSC_AHB_CLK_ID                   0xD594BB06
#define DISP_CC_MDSS_PCLK0_CLK_ID                          0xDF2F28DF
#define DISP_CC_MDSS_PCLK1_CLK_ID                          0xEC01E1B5
#define DISP_CC_MDSS_PCLK2_CLK_ID                          0x5300F6F4
#define DISP_CC_MDSS_RSCC_AHB_CLK_ID                       0x23666C25
#define DISP_CC_MDSS_RSCC_VSYNC_CLK_ID                     0x47CD7D13
#define DISP_CC_MDSS_SPDM_DEBUG_CLK_ID                     0x1B862752
#define DISP_CC_MDSS_SPDM_DEBUG_DIV_CLK_SRC_ID             0xEE3A2D86
#define DISP_CC_MDSS_SPDM_DP_CRYPTO_CLK_ID                 0x75EFBB45
#define DISP_CC_MDSS_SPDM_DP_CRYPTO_DIV_CLK_SRC_ID         0x92140365
#define DISP_CC_MDSS_SPDM_DP_PIXEL1_CLK_ID                 0x24157A60
#define DISP_CC_MDSS_SPDM_DP_PIXEL1_DIV_CLK_SRC_ID         0xBA7C3FFE
#define DISP_CC_MDSS_SPDM_DP_PIXEL_CLK_ID                  0x72B57E57
#define DISP_CC_MDSS_SPDM_DP_PIXEL_DIV_CLK_SRC_ID          0xB91A8101
#define DISP_CC_MDSS_SPDM_MDP_CLK_ID                       0x8D7A3901
#define DISP_CC_MDSS_SPDM_MDP_DIV_CLK_SRC_ID               0xF50D25B5
#define DISP_CC_MDSS_SPDM_PCLK0_CLK_ID                     0x757CD20E
#define DISP_CC_MDSS_SPDM_PCLK0_DIV_CLK_SRC_ID             0xC1F3C754
#define DISP_CC_MDSS_SPDM_PCLK1_CLK_ID                     0x3C6FD75A
#define DISP_CC_MDSS_SPDM_PCLK1_DIV_CLK_SRC_ID             0xC61F8E9C
#define DISP_CC_MDSS_SPDM_PCLK2_CLK_ID                     0x8251975E
#define DISP_CC_MDSS_SPDM_PCLK2_DIV_CLK_SRC_ID             0xC66D56A6
#define DISP_CC_MDSS_VSYNC1_CLK_ID                         0x106D4032
#define DISP_CC_MDSS_VSYNC_CLK_ID                          0x80004355
#define DISP_CC_OSC_CLK_ID                                 0x77D41E59
#define DISP_CC_PLL0_ID                                    0x4C3DD57F
#define DISP_CC_PLL1_ID                                    0xECE07681
#define DISP_CC_PLL2_ID                                    0x3FB0F6DD
#define DISP_CC_PLL_TEST_CLK_ID                            0x7D7A63ED
#define DISP_CC_PLL_TEST_DIV_CLK_SRC_ID                    0x2DF2D452
#define DISP_CC_SLEEP_CLK_ID                               0xE16C7ED9
#define DISP_CC_XO_CLK_ID                                  0x9C4A81EA
#define EVA_CC_AHB_CLK_ID                                  0x168AED7A
#define EVA_CC_DEBUG_CLK_ID                                0x73F682B8
#define EVA_CC_DEBUG_DIV_CLK_SRC_ID                        0x6E2A05B7
#define EVA_CC_DEBUG_MUX_ID                                0xFB278A6F
#define EVA_CC_MVS0_CLK_ID                                 0x567EC029
#define EVA_CC_MVS0_DIV_CLK_SRC_ID                         0x182486DD
#define EVA_CC_MVS0_FREERUN_CLK_ID                         0x6B5B6879
#define EVA_CC_MVS0_GDSC_ID                                0x510D7091
#define EVA_CC_MVS0_SHIFT_CLK_ID                           0xD8172FD3
#define EVA_CC_MVS0C_CLK_ID                                0x2A938F09
#define EVA_CC_MVS0C_DIV2_DIV_CLK_SRC_ID                   0x518D36A8
#define EVA_CC_MVS0C_DIV_CLK_SRC_ID                        0x81C01E67
#define EVA_CC_MVS0C_FREERUN_CLK_ID                        0x6080F112
#define EVA_CC_MVS0C_GDSC_ID                               0x9D032B08
#define EVA_CC_MVS0C_SHIFT_CLK_ID                          0xDD631115
#define EVA_CC_PLL0_ID                                     0xD1D8963F
#define EVA_CC_PLL_TEST_CLK_ID                             0x96D86251
#define EVA_CC_PLL_TEST_DIV_CLK_SRC_ID                     0x84659F97
#define EVA_CC_SLEEP_CLK_ID                                0x6989C6B0
#define EVA_CC_XO_CLK_ID                                   0xDB1A19FE
#define GCC_AGGRE_NOC_PCIE_AXI_CLK_ID                      0x7F143CA9
#define GCC_AGGRE_UFS_PHY_AXI_CLK_ID                       0x9D270053
#define GCC_AGGRE_USB3_PRIM_AXI_CLK_ID                     0x9C0C2B41
#define GCC_BOOT_ROM_AHB_CLK_ID                            0x20C2EB7C
#define GCC_CAM_BIST_MCLK_AHB_CLK_ID                       0xAA1CD05B
#define GCC_CAMERA_AHB_CLK_ID                              0xCB81AAEC
#define GCC_CAMERA_HF_AXI_CLK_ID                           0x62191536
#define GCC_CAMERA_SF_AXI_CLK_ID                           0x033685A3
#define GCC_CAMERA_XO_CLK_ID                               0xEF993118
#define GCC_CFG_NOC_PCIE_ANOC_AHB_CLK_ID                   0x927E2559
#define GCC_CFG_NOC_USB3_PRIM_AXI_CLK_ID                   0xE7023B78
#define GCC_CNOC_PCIE_SF_AXI_CLK_ID                        0xF1E3FEDD
#define GCC_DDRSS_GPU_AXI_CLK_ID                           0xDF8E077C
#define GCC_DDRSS_PCIE_SF_QTB_CLK_ID                       0x6872C48B
#define GCC_DEBUG_MUX_ID                                   0x53CF8DFF
#define GCC_DISP_AHB_CLK_ID                                0xCC324D48
#define GCC_DISP_HF_AXI_CLK_ID                             0xBF311160
#define GCC_EVA_AHB_CLK_ID                                 0xBE0BFD17
#define GCC_EVA_AXI0_CLK_ID                                0x7FB564E4
#define GCC_EVA_AXI0C_CLK_ID                               0x422FA85E
#define GCC_EVA_XO_CLK_ID                                  0x65DBE626
#define GCC_GP1_CLK_ID                                     0x5BCD42D6
#define GCC_GP2_CLK_ID                                     0xC0B86CC1
#define GCC_GP3_CLK_ID                                     0x81385E59
#define GCC_GPLL0_ID                                       0x799CE72B
#define GCC_GPLL0_UFS_PHY_RX_SYMBOL_0_CLK_ID               0x106963AD
#define GCC_GPLL0_UFS_PHY_RX_SYMBOL_0_DIV_CLK_SRC_ID       0xE2B0632E
#define GCC_GPLL0_UFS_PHY_RX_SYMBOL_1_CLK_ID               0x9A09B4DA
#define GCC_GPLL0_UFS_PHY_RX_SYMBOL_1_DIV_CLK_SRC_ID       0x8E32C3F7
#define GCC_GPLL0_UFS_PHY_TX_SYMBOL_0_CLK_ID               0x098D4A5E
#define GCC_GPLL0_UFS_PHY_TX_SYMBOL_0_DIV_CLK_SRC_ID       0xB63D9CE4
#define GCC_GPLL4_ID                                       0xF99FC9C2
#define GCC_GPLL7_ID                                       0x7B8FE8F0
#define GCC_GPLL9_ID                                       0xF7CEA735
#define GCC_GPU_CFG_AHB_CLK_ID                             0xBDC5D904
#define GCC_GPU_GEMNOC_CLK_EN_ID                           0x0DE82A26
#define GCC_GPU_GEMNOC_GFX_CLK_EN_ID                       0xDFBC701E
#define GCC_GPU_GEMNOC_GFX_CLK_ID                          0xA110C494
#define GCC_GPU_GEMNOC_GFX_DCD_CDIV_CLK_SRC_ID             0xDBA070B9
#define GCC_GPU_GPLL0_CLK_SRC_ID                           0x4B1A4AC7
#define GCC_GPU_GPLL0_DIV_CLK_SRC_ID                       0x6EEEF079
#define GCC_GPU_PLL0_MAIN_DIV_CLK_SRC_ID                   0x1D106BCF
#define GCC_GPU_SMMU_VOTE_CLK_ID                           0x07E6B1F8
#define GCC_GPU_SMMU_VOTE_GDS_ID                           0xFAFFC514
#define GCC_GPU_TRIG_DIV_CLK_SRC_ID                        0x74E54DEE
#define GCC_HLOS1_VOTE_AGGRE_NOC_MMU_PCIE_QTB_CLK_ID       0x28F54D89
#define GCC_HLOS1_VOTE_AGGRE_NOC_MMU_PCIE_QTB_GDS_ID       0x74DB78FD
#define GCC_HLOS1_VOTE_AGGRE_NOC_MMU_QTB1_CLK_ID           0xAE4D1A85
#define GCC_HLOS1_VOTE_AGGRE_NOC_MMU_QTB1_GDS_ID           0xC3798F08
#define GCC_HLOS1_VOTE_AGGRE_NOC_MMU_QTB2_CLK_ID           0x32CEE595
#define GCC_HLOS1_VOTE_AGGRE_NOC_MMU_QTB2_GDS_ID           0x08B324B4
#define GCC_HLOS1_VOTE_ALL_SMMU_MMU_CLK_ID                 0xF26FB3CE
#define GCC_HLOS1_VOTE_ALL_SMMU_MMU_GDS_ID                 0xBAACE2AF
#define GCC_HLOS1_VOTE_DDRSS_UBWCP_QTB_CLK_ID              0xBC6B2B58
#define GCC_HLOS1_VOTE_DDRSS_UBWCP_QTB_GDS_ID              0x24CE219A
#define GCC_HLOS1_VOTE_GPU_SMMU_CLK_ID                     0x4A750D50
#define GCC_HLOS1_VOTE_GPU_SMMU_GDS_ID                     0x0F149500
#define GCC_HLOS1_VOTE_LPASS_QTB_CLK_ID                    0xD0D3E743
#define GCC_HLOS1_VOTE_LPASS_QTB_GDS_ID                    0xDEAABDAA
#define GCC_HLOS1_VOTE_MMNOC_MMU_QTB_HF01_CLK_ID           0x783936F7
#define GCC_HLOS1_VOTE_MMNOC_MMU_QTB_HF01_GDS_ID           0x1E8A798A
#define GCC_HLOS1_VOTE_MMNOC_MMU_QTB_HF23_CLK_ID           0xFE40C8DA
#define GCC_HLOS1_VOTE_MMNOC_MMU_QTB_HF23_GDS_ID           0x87D675C7
#define GCC_HLOS1_VOTE_MMNOC_MMU_QTB_SF_CLK_ID             0x585A9AF6
#define GCC_HLOS1_VOTE_MMNOC_MMU_QTB_SF_GDS_ID             0xEF85DE46
#define GCC_HLOS1_VOTE_MMU_TCU_CLK_ID                      0x45B7596F
#define GCC_HLOS1_VOTE_MMU_TCU_GDS_ID                      0x4A5857B9
#define GCC_HLOS1_VOTE_TURING_MMU_QTB0_CLK_ID              0xD20C70A8
#define GCC_HLOS1_VOTE_TURING_MMU_QTB0_GDS_ID              0x29D59788
#define GCC_MMU_TCU_VOTE_CLK_ID                            0xC9C1BCE8
#define GCC_MMU_TCU_VOTE_GDS_ID                            0x6AF2E227
#define GCC_PCIE_0_AUX_CLK_ID                              0xDE4195A6
#define GCC_PCIE_0_CFG_AHB_CLK_ID                          0xAB33D8F8
#define GCC_PCIE_0_GDSC_ID                                 0xC1C9C0D4
#define GCC_PCIE_0_LINK_DOWN_BCR_ID                        0xB6C4C692
#define GCC_PCIE_0_MSTR_AXI_CLK_ID                         0x6ECCBB13
#define GCC_PCIE_0_NOCSR_COM_PHY_BCR_ID                    0xD13C8283
#define GCC_PCIE_0_PHY_BCR_ID                              0x822A9820
#define GCC_PCIE_0_PHY_GDSC_ID                             0x2AE8F85B
#define GCC_PCIE_0_PHY_NOCSR_COM_PHY_BCR_ID                0xA7917945
#define GCC_PCIE_0_PHY_RCHNG_CLK_ID                        0x4F8DB026
#define GCC_PCIE_0_PIPE_CLK_ID                             0xDCB72BF8
#define GCC_PCIE_0_SLV_AXI_CLK_ID                          0x9331B3EF
#define GCC_PCIE_0_SLV_Q2A_AXI_CLK_ID                      0x5B161349
#define GCC_PCIE_PHY_BCR_ID                                0x7D75D7C2
#define GCC_PCIE_PHY_CFG_AHB_BCR_ID                        0x5FB6DA8B
#define GCC_PCIE_PHY_COM_BCR_ID                            0x20D7AA6B
#define GCC_PCIE_RSCC_AHB_CLK_ID                           0x4723F290
#define GCC_PCIE_RSCC_XO_CLK_ID                            0xEE38661C
#define GCC_PDM2_CLK_ID                                    0xF8EA86EA
#define GCC_PDM_AHB_CLK_ID                                 0xA6F0A072
#define GCC_PDM_XO4_CLK_ID                                 0x1C323047
#define GCC_PDM_XO4_DIV_CLK_SRC_ID                         0x45668877
#define GCC_QDSS_ATB_B_CLK_SRC_ID                          0xCD881BBE
#define GCC_QDSS_ATB_B_CLK_SRC_ID                          0xCD881BBE
#define GCC_QDSS_TRIG_CLK_SRC_ID                           0x822AE1B2
#define GCC_QDSS_TRIG_CLK_SRC_ID                           0x822AE1B2
#define GCC_QMIP_CAMERA_CMD_AHB_CLK_ID                     0x3AE14BF7
#define GCC_QMIP_CAMERA_NRT_AHB_CLK_ID                     0x5508D425
#define GCC_QMIP_CAMERA_RT_AHB_CLK_ID                      0x15F7C6F4
#define GCC_QMIP_GPU_AHB_CLK_ID                            0x428F6D35
#define GCC_QMIP_PCIE_AHB_CLK_ID                           0x508920D5
#define GCC_QMIP_VIDEO_CV_CPU_AHB_CLK_ID                   0x0F770842
#define GCC_QMIP_VIDEO_CVP_AHB_CLK_ID                      0x5577C832
#define GCC_QMIP_VIDEO_V_CPU_AHB_CLK_ID                    0x39939E99
#define GCC_QMIP_VIDEO_VCODEC_AHB_CLK_ID                   0xED09B49D
#define GCC_QUPV3_I2C_CORE_CLK_ID                          0x3E8231C8
#define GCC_QUPV3_I2C_S0_CLK_ID                            0x2897A430
#define GCC_QUPV3_I2C_S1_CLK_ID                            0x0D97F42A
#define GCC_QUPV3_I2C_S2_CLK_ID                            0x861954F9
#define GCC_QUPV3_I2C_S3_CLK_ID                            0x3D0024FA
#define GCC_QUPV3_I2C_S4_CLK_ID                            0xF13B341C
#define GCC_QUPV3_I2C_S5_CLK_ID                            0x693008C9
#define GCC_QUPV3_I2C_S6_CLK_ID                            0xE9029DB8
#define GCC_QUPV3_I2C_S7_CLK_ID                            0xA5205A17
#define GCC_QUPV3_I2C_S8_CLK_ID                            0xA75C6ECF
#define GCC_QUPV3_I2C_S9_CLK_ID                            0x4CE705D0
#define GCC_QUPV3_I2C_S_AHB_CLK_ID                         0x3B084431
#define GCC_QUPV3_WRAP1_CORE_2X_CLK_ID                     0xD7DB82C0
#define GCC_QUPV3_WRAP1_CORE_CLK_ID                        0x40B685B0
#define GCC_QUPV3_WRAP1_CORE_DIV_CLK_SRC_ID                0x9C4D8275
#define GCC_QUPV3_WRAP1_QSPI_REF_CLK_ID                    0x386E7E5A
#define GCC_QUPV3_WRAP1_S0_CLK_ID                          0xA40B3E1C
#define GCC_QUPV3_WRAP1_S1_CLK_ID                          0xDE8BDAAC
#define GCC_QUPV3_WRAP1_S2_CLK_ID                          0x45AB34F6
#define GCC_QUPV3_WRAP1_S2_CLK_SRC_ID                      0x0054935A
#define GCC_QUPV3_WRAP1_S3_CLK_ID                          0x6CBC20FD
#define GCC_QUPV3_WRAP1_S4_CLK_ID                          0x2A814B46
#define GCC_QUPV3_WRAP1_S5_CLK_ID                          0x8279058C
#define GCC_QUPV3_WRAP1_S6_CLK_ID                          0x6FB2266A
#define GCC_QUPV3_WRAP1_S7_CLK_ID                          0x90473589
#define GCC_QUPV3_WRAP2_CORE_2X_CLK_ID                     0x70CC1B69
#define GCC_QUPV3_WRAP2_CORE_CLK_ID                        0xAC5F6885
#define GCC_QUPV3_WRAP2_CORE_DIV_CLK_SRC_ID                0x71FFA9A3
#define GCC_QUPV3_WRAP2_IBI_CTRL_2_CLK_ID                  0xF1BF54D2
#define GCC_QUPV3_WRAP2_IBI_CTRL_3_CLK_ID                  0x47DC68A6
#define GCC_QUPV3_WRAP2_S0_CLK_ID                          0x62380FFF
#define GCC_QUPV3_WRAP2_S1_CLK_ID                          0xF02791D2
#define GCC_QUPV3_WRAP2_S2_CLK_ID                          0xA5E32B19
#define GCC_QUPV3_WRAP2_S3_CLK_ID                          0xEEF92C79
#define GCC_QUPV3_WRAP2_S4_CLK_ID                          0x7980B17E
#define GCC_QUPV3_WRAP2_S5_CLK_ID                          0x9777FCA3
#define GCC_QUPV3_WRAP2_S6_CLK_ID                          0x232CDACA
#define GCC_QUPV3_WRAP2_S7_CLK_ID                          0xF372099E
#define GCC_QUPV3_WRAP_1_M_AHB_CLK_ID                      0x728861DF
#define GCC_QUPV3_WRAP_1_S_AHB_CLK_ID                      0x3428967E
#define GCC_QUPV3_WRAP_2_IBI_2_AHB_CLK_ID                  0x20E6AA7C
#define GCC_QUPV3_WRAP_2_IBI_3_AHB_CLK_ID                  0xE9A86650
#define GCC_QUPV3_WRAP_2_M_AHB_CLK_ID                      0xFBEA7E74
#define GCC_QUPV3_WRAP_2_S_AHB_CLK_ID                      0x306EA255
#define GCC_QUSB2PHY_PRIM_BCR_ID                           0x9E2329D1
#define GCC_QUSB2PHY_SEC_BCR_ID                            0x7D3CC967
#define GCC_SDCC2_AHB_CLK_ID                               0xF7AE64AF
#define GCC_SDCC2_APPS_CLK_ID                              0x99917219
#define GCC_SDCC2_AT_CLK_ID                                0x63F0B54C
#define GCC_SDCC4_AHB_CLK_ID                               0xB1EE1963
#define GCC_SDCC4_APPS_CLK_ID                              0x582886BC
#define GCC_SDCC4_AT_CLK_ID                                0x228145F3
#define GCC_UFS_MEM_PHY_GDSC_ID                            0xF7004938
#define GCC_UFS_PHY_AHB_CLK_ID                             0x79B5465B
#define GCC_UFS_PHY_AXI_CLK_ID                             0x9310F430
#define GCC_UFS_PHY_GDSC_ID                                0x0B76D452
#define GCC_UFS_PHY_ICE_CORE_CLK_ID                        0xEB42CB41
#define GCC_UFS_PHY_PHY_AUX_CLK_ID                         0x224FBCE6
#define GCC_UFS_PHY_RX_SYMBOL_0_CLK_ID                     0xC250BA4B
#define GCC_UFS_PHY_RX_SYMBOL_1_CLK_ID                     0xB7C57145
#define GCC_UFS_PHY_TX_SYMBOL_0_CLK_ID                     0xDE965215
#define GCC_UFS_PHY_UNIPRO_CORE_CLK_ID                     0x815C816D
#define GCC_USB30_PRIM_GDSC_ID                             0x8DA85DD3
#define GCC_USB30_PRIM_MASTER_CLK_ID                       0x91482B7C
#define GCC_USB30_PRIM_MOCK_UTMI_CLK_ID                    0xFEDF50FF
#define GCC_USB30_PRIM_MOCK_UTMI_POSTDIV_CLK_SRC_ID        0x33EBC056
#define GCC_USB30_PRIM_SLEEP_CLK_ID                        0xA3AD9ACB
#define GCC_USB3_DP_PHY_PRIM_BCR_ID                        0x1F251390
#define GCC_USB3_DP_PHY_SEC_BCR_ID                         0x6969477E
#define GCC_USB3_PHY_GDSC_ID                               0x03ED0944
#define GCC_USB3_PHY_PRIM_BCR_ID                           0x7F6A6E8C
#define GCC_USB3_PHY_SEC_BCR_ID                            0xA8BC18B6
#define GCC_USB3_PRIM_PHY_AUX_CLK_ID                       0x5BBF945A
#define GCC_USB3_PRIM_PHY_COM_AUX_CLK_ID                   0x84C54E8E
#define GCC_USB3_PRIM_PHY_PIPE_CLK_ID                      0x8F9EA437
#define GCC_USB3PHY_PHY_PRIM_BCR_ID                        0x12166FD9
#define GCC_USB3PHY_PHY_SEC_BCR_ID                         0x5ECE2A2C
#define GCC_VIDEO_AHB_CLK_ID                               0x3DC15104
#define GCC_VIDEO_AXI0_CLK_ID                              0x527C9897
#define GCC_VIDEO_AXI1_CLK_ID                              0x4F8C5CD6
#define GCC_VIDEO_XO_CLK_ID                                0x79581D18
#define GPU_CC_AHB_CLK_ID                                  0x763BA1C4
#define GPU_CC_CB_CLK_ID                                   0x721C91D0
#define GPU_CC_CX_ACCU_SHIFT_CLK_ID                        0x2F27F55F
#define GPU_CC_CX_APB_CLK_ID                               0x6E5557EC
#define GPU_CC_CX_FF_CLK_ID                                0x276A4142
#define GPU_CC_CX_GDSC_ID                                  0x9C476251
#define GPU_CC_CX_GMU_CLK_ID                               0x85040864
#define GPU_CC_CX_QDSS_AT_CLK_ID                           0x3A64CC97
#define GPU_CC_CX_QDSS_TRIG_CLK_ID                         0x046DFEBA
#define GPU_CC_CX_QDSS_TSCTR_CLK_ID                        0x403CC85F
#define GPU_CC_CXO_AON_CLK_ID                              0xA006B60F
#define GPU_CC_CXO_CLK_ID                                  0x8DFA73CF
#define GPU_CC_DEBUG_CLK_ID                                0x2D49728D
#define GPU_CC_DEBUG_DIV_CLK_SRC_ID                        0x5614E81D
#define GPU_CC_DEBUG_MEASURE_CLK_ID                        0x61D27566
#define GPU_CC_DEBUG_MUX_ID                                0x89008681
#define GPU_CC_DEMET_CLK_ID                                0x2217FC16
#define GPU_CC_DEMET_DIV_CLK_SRC_ID                        0xA02475AF
#define GPU_CC_DPM_CLK_ID                                  0xF3ECE45F
#define GPU_CC_FREQ_MEASURE_CLK_ID                         0xC306597F
#define GPU_CC_GPU_SMMU_VOTE_CLK_ID                        0x77CA04D1
#define GPU_CC_GPU_SMMU_VOTE_GDS_ID                        0x9BBCA751
#define GPU_CC_GX_ACCU_SHIFT_CLK_ID                        0x5EAB0BB8
#define GPU_CC_GX_ACD_AHB_FF_CLK_ID                        0x80DCC665
#define GPU_CC_GX_AHB_FF_CLK_ID                            0x1DDFC79F
#define GPU_CC_GX_GMU_CLK_ID                               0xFD46B6AB
#define GPU_CC_GX_RCG_AHB_FF_CLK_ID                        0x3A012F1F
#define GPU_CC_HLOS1_VOTE_GPU_SMMU_CLK_ID                  0xF6733823
#define GPU_CC_HUB_AON_CLK_ID                              0x063271D7
#define GPU_CC_HUB_CX_INT_CLK_ID                           0xC00F7891
#define GPU_CC_HUB_DIV_CLK_SRC_ID                          0x6E8F44EF
#define GPU_CC_MEMNOC_GFX_CLK_ID                           0xEAA2A911
#define GPU_CC_MEMNOC_GFX_CPL_CLK_SRC_ID                   0xE7B1BD63
#define GPU_CC_PLL0_ID                                     0x858FC27E
#define GPU_CC_PLL_TEST_CLK_ID                             0x8F8278F9
#define GPU_CC_PLL_TEST_DIV_CLK_SRC_ID                     0x13284B79
#define GPU_CC_RSCC_HUB_AON_CLK_ID                         0x24095AAA
#define GPU_CC_RSCC_XO_AON_CLK_ID                          0xC5B136B0
#define GPU_CC_SLEEP_CLK_ID                                0xC2E1C465
#define GPU_CC_XO_DIV_CLK_SRC_ID                           0x6DA2BFA1
#define GPUCC_GPU_CC_FF_BCR_ID                             0x30673FAE
#define GPUCC_GPU_CC_GMU_BCR_ID                            0xB67BB00E
#define GX_CLKCTL_ACD_CXO_CLK_ID                           0x7CDADA98
#define GX_CLKCTL_ACD_GFX3D_CLK_ID                         0x875D0742
#define GX_CLKCTL_CLK_CTL_XO_CLK_ID                        0x0484D786
#define GX_CLKCTL_DEBUG_CLK_ID                             0xED4C92E9
#define GX_CLKCTL_DEBUG_MUX_ID                             0xA858A01C
#define GX_CLKCTL_DEMET_CLK_ID                             0xC0027370
#define GX_CLKCTL_GX_ACCU_CLK_ID                           0xAC6923DC
#define GX_CLKCTL_GX_CXO_CLK_ID                            0x0EEDCC51
#define GX_CLKCTL_GX_GDSC_ID                               0xC37292D5
#define GX_CLKCTL_GX_GFX3D_CLK_ID                          0x45536680
#define GX_CLKCTL_GX_GFX3D_DIV_CLK_SRC_ID                  0x16932E80
#define GX_CLKCTL_GX_GFX3D_RDVM_CLK_ID                     0xDF5E9C40
#define GX_CLKCTL_MND1X_GFX3D_CLK_ID                       0xB0A24B93
#define GX_CLKCTL_PLL0_ID                                  0x8945FE1A
#define GX_CLKCTL_PLL_TEST_CLK_ID                          0x9F45DA64
#define GX_CLKCTL_PLL_TEST_DIV_CLK_SRC_ID                  0xCD670337
#define GX_CLKCTL_XO_CLK_DIV_CLK_SRC_ID                    0x456174A0
#define TCSR_PCIE_0_CLKREF_EN_ID                           0x46A80F38
#define TCSR_UFS_CLKREF_EN_ID                              0xC269EEF4
#define TCSR_USB2_CLKREF_EN_ID                             0xA3B407A1
#define TCSR_USB3_CLKREF_EN_ID                             0x3A592B58
#define VIDEO_CC_AHB_CLK_ID                                0x12DABE26
#define VIDEO_CC_DEBUG_CLK_ID                              0x9AD7014D
#define VIDEO_CC_DEBUG_DIV_CLK_SRC_ID                      0xF29AA514
#define VIDEO_CC_DEBUG_MUX_ID                              0xE8021679
#define VIDEO_CC_MVS0_CLK_ID                               0x69F9979C
#define VIDEO_CC_MVS0_DIV_CLK_SRC_ID                       0x6EC8765C
#define VIDEO_CC_MVS0_FREERUN_CLK_ID                       0x8C4B765C
#define VIDEO_CC_MVS0_GDSC_ID                              0x0C6A70FC
#define VIDEO_CC_MVS0_SHIFT_CLK_ID                         0x0DB0D3BC
#define VIDEO_CC_MVS0C_CLK_ID                              0xCC22911E
#define VIDEO_CC_MVS0C_DIV2_DIV_CLK_SRC_ID                 0xF9B6D090
#define VIDEO_CC_MVS0C_DIV_CLK_SRC_ID                      0x6D4B044F
#define VIDEO_CC_MVS0C_FREERUN_CLK_ID                      0x2B7DE545
#define VIDEO_CC_MVS0C_GDSC_ID                             0x07EA7371
#define VIDEO_CC_MVS0C_SHIFT_CLK_ID                        0x7E371A11
#define VIDEO_CC_PLL0_ID                                   0xD9130185
#define VIDEO_CC_PLL_TEST_CLK_ID                           0xF56D61DD
#define VIDEO_CC_PLL_TEST_DIV_CLK_SRC_ID                   0x3AD246DE
#define VIDEO_CC_SLEEP_CLK_ID                              0x2CE12181
#define VIDEO_CC_XO_CLK_ID                                 0x3777936C
#define LPASS_AON_CC_AON_H_CLK_ID                          0x126C9D36
#define LPASS_AON_CC_AON_NOC_AT_CLK_ID                     0xAF6D1006
#define LPASS_AON_CC_AON_NOC_CLK_ID                        0x6035904A
#define LPASS_AON_CC_AON_NOC_QDSS_TSCTR_CLK_ID             0xFCECF7E6
#define LPASS_AON_CC_AON_NOC_XO_CLK_ID                     0xFD71431C
#define LPASS_AON_CC_AT_CLK_ID                             0x68B5F979
#define LPASS_AON_CC_AUDIO_HM_H_CLK_ID                     0xB6FC4401
#define LPASS_AON_CC_AUDIO_HM_NIU_CLK_ID                   0xEAB8DE17
#define LPASS_AON_CC_AUDIO_HM_NIU_MASTER_CLK_ID            0x664C5FA5
#define LPASS_AON_CC_AUDIO_HM_SLEEP_CLK_ID                 0x0D66E6FB
#define LPASS_AON_CC_AWM_CTI_CLK_ID                        0x7C5674A6
#define LPASS_AON_CC_AWM_CTI_PCLK_CLK_ID                   0x1923B939
#define LPASS_AON_CC_AWM_DAP_CLK_ID                        0xFBD33EF9
#define LPASS_AON_CC_AWM_MEM_BCR_ID                        0xE6EC4648
#define LPASS_AON_CC_AWM_QDSS_CLK_ID                       0xFF6D256A
#define LPASS_AON_CC_AWM_TS_CLK_ID                         0x81F4FDE6
#define LPASS_AON_CC_AWM_XO_CLK_ID                         0xDB990586
#define LPASS_AON_CC_BROADCAST_CLK_ID                      0x60D82ABA
#define LPASS_AON_CC_CPR_CLK_ID                            0x584AEDCF
#define LPASS_AON_CC_CPR_H_CLK_ID                          0x32B69BC2
#define LPASS_AON_CC_CSR_H_CLK_ID                          0x1856A226
#define LPASS_AON_CC_DBG_TSCTR_CLK_ID                      0x48CA7215
#define LPASS_AON_CC_DEBUG_CLK_ID                          0x79E0A71A
#define LPASS_AON_CC_DEBUG_DIV_CLK_SRC_ID                  0xAE31AB3A
#define LPASS_AON_CC_DEBUG_MUX_ID                          0x276A70A8
#define LPASS_AON_CC_ENPU_SCHEDULER_CLK_ID                 0x0FE4E437
#define LPASS_AON_CC_ENPU_SCHEDULER_H_CLK_ID               0x596DFA44
#define LPASS_AON_CC_ENPU_SCHEDULER_QSB_CLK_ID             0x7A81BEF8
#define LPASS_AON_CC_ICB_LINK_CLK_ID                       0x767081CA
#define LPASS_AON_CC_IPCMEM_CLK_ID                         0x5138C9B2
#define LPASS_AON_CC_LPASS_0_LPMLA_AHB_ODSC_CLK_ID         0x242E0846
#define LPASS_AON_CC_LPASS_0_LPMLA_ENPU_NOC_AT_CLK_ID      0xD45D6201
#define LPASS_AON_CC_LPASS_0_LPMLA_ENPU_NOC_QDSS_TSCTR_CLK_ID 0xA7EC65C5
#define LPASS_AON_CC_LPASS_0_LPMLA_H_CLK_ID                0xFCE893D0
#define LPASS_AON_CC_LPASS_0_LPMLA_NOC_CLK_ID              0x0305C6CA
#define LPASS_AON_CC_LPASS_0_LPMLA_NOC_XO_CLK_ID           0x3F3324A7
#define LPASS_AON_CC_LPASS_1_LPMLA_AHB_ODSC_CLK_ID         0x30E54B8B
#define LPASS_AON_CC_LPASS_1_LPMLA_ENPU_NOC_AT_CLK_ID      0x87AE7BD6
#define LPASS_AON_CC_LPASS_1_LPMLA_ENPU_NOC_QDSS_TSCTR_CLK_ID 0xD6814ECA
#define LPASS_AON_CC_LPASS_1_LPMLA_H_CLK_ID                0x0318564B
#define LPASS_AON_CC_LPASS_1_LPMLA_NOC_CLK_ID              0x27BC0F94
#define LPASS_AON_CC_LPASS_1_LPMLA_NOC_XO_CLK_ID           0x925CF34A
#define LPASS_AON_CC_LPASS_AUDIO_HM_AT_CLK_ID              0xE258D8C7
#define LPASS_AON_CC_LPASS_AUDIO_HM_GDSC_ID                0x86F7ADED
#define LPASS_AON_CC_LPASS_AUDIO_HM_PCLKDBG_CLK_ID         0x47F3CC1F
#define LPASS_AON_CC_LPASS_AUDIO_HM_TSCTR_CLK_ID           0xC22CDAC9
#define LPASS_AON_CC_LPASS_PDC_HM_GDSC_ID                  0xDBEFA5C4
#define LPASS_AON_CC_LPI_NOC_DBG_CLK_ID                    0x9672EC09
#define LPASS_AON_CC_LPI_NOC_HS_CLK_ID                     0xDA2A2D97
#define LPASS_AON_CC_LPI_NOC_HS_DCD_DIV_CLK_SRC_ID         0x35D81E11
#define LPASS_AON_CC_LPI_NOC_LS_CLK_ID                     0x1CC2D80A
#define LPASS_AON_CC_LPI_NOC_MPU_CFG_CLK_ID                0xE4A916D4
#define LPASS_AON_CC_LPI_NOC_XO_CLK_ID                     0x6EA95F05
#define LPASS_AON_CC_LPICX_NOC_CLK_ID                      0x5313215F
#define LPASS_AON_CC_MCC_ACCESS_CLK_ID                     0x7E485C61
#define LPASS_AON_CC_PCLKDBG_CLK_ID                        0x8680CEB2
#define LPASS_AON_CC_PDC_GDS_CLK_ID                        0x57B66F58
#define LPASS_AON_CC_PDC_H_CLK_ID                          0x287114E9
#define LPASS_AON_CC_PLL_ID                                0xF70601B5
#define LPASS_AON_CC_PLL_LV_TEST_CLK_ID                    0x55C82ECE
#define LPASS_AON_CC_PLL_LV_TEST_POSTDIV_DIV_CLK_SRC_ID    0xB501B93E
#define LPASS_AON_CC_PLL_OUT_EVEN_PWRGRP2_CLKGEN_ACGC_CLK_ID 0x1EB94712
#define LPASS_AON_CC_PLL_OUT_EVEN_PWRGRP2_CLKGEN_ACGC_CLK_ID 0x1EB94712
#define LPASS_AON_CC_PLL_OUT_MAIN_ACGC_CLK_ID              0x8333042D
#define LPASS_AON_CC_PLL_OUT_MAIN_LLCC_DCD_DIV_CLK_SRC_ID  0x5DA1F753
#define LPASS_AON_CC_PLL_OUT_MAIN_PWRGRP0_CLKGEN_ACGC_CLK_ID 0x591221F1
#define LPASS_AON_CC_PLL_OUT_MAIN_SSC_CDIV_DIV_CLK_SRC_ID  0x0A284615
#define LPASS_AON_CC_Q6_AHBM_CLK_ID                        0xA2DF9551
#define LPASS_AON_CC_Q6_AHBS_CLK_ID                        0x084CE6DD
#define LPASS_AON_CC_Q6_ATBM_CLK_ID                        0x684901D1
#define LPASS_AON_CC_Q6_AXIM_CLK_ID                        0x9443892A
#define LPASS_AON_CC_Q6_AXIS_CLK_ID                        0xA84D006F
#define LPASS_AON_CC_Q6_DEBUG_MUX_ID                       0xE6334AC4
#define LPASS_AON_CC_Q6_XO_CLK_ID                          0x547EA764
#define LPASS_AON_CC_RO_CLK_ID                             0xE74D0BB4
#define LPASS_AON_CC_SEQ_H_CLK_ID                          0x6E8556EA
#define LPASS_AON_CC_SEQ_XPU_CLK_ID                        0xD6CDC7C6
#define LPASS_AON_CC_SEQUENCER_MCLK_CLK_ID                 0x5D03D76B
#define LPASS_AON_CC_SEQUENCER_MCLK_DIV_CLK_SRC_ID         0xC9DFDFE1
#define LPASS_AON_CC_SLEEP_CLK_ID                          0x46A0FD89
#define LPASS_AON_CC_SSC_H_MASTER_CLK_ID                   0x998AA997
#define LPASS_AON_CC_SSC_H_SLAVE_CLK_ID                    0x62789EA4
#define LPASS_AON_CC_SWM_CTI_CLK_ID                        0x5D8E7EB2
#define LPASS_AON_CC_SWM_CTI_PCLK_CLK_ID                   0xA63FD01D
#define LPASS_AON_CC_SWM_DAP_CLK_ID                        0x2C665F20
#define LPASS_AON_CC_SWM_MEM_BCR_ID                        0x8DADBAEA
#define LPASS_AON_CC_SWM_QDSS_CLK_ID                       0x87D2935F
#define LPASS_AON_CC_SWM_TS_CLK_ID                         0x7108A171
#define LPASS_AON_CC_SWM_XO_CLK_ID                         0x7CD91341
#define LPASS_AON_CC_VS_VDDCX_CLK_ID                       0x03DE5C94
#define LPASS_AON_CC_VS_VDDMX_CLK_ID                       0xA94CBA5E
#define LPASS_AON_CC_WDSS_AT_CLK_ID                        0x415BAB1E
#define LPASS_AON_CC_WDSS_CORE_BCR_ID                      0x32826088
#define LPASS_AON_CC_WDSS_DBG_TSCTR_CLK_ID                 0x55936386
#define LPASS_AON_CC_XO_DIV16_CLK_ID                       0x7BE0E103
#define LPASS_AON_CC_XO_DIV16_DIV_CLK_SRC_ID               0xAB6E6C37
#define LPASS_AON_MX_CC_AAD_CLK_ID                         0x11228D91
#define LPASS_AON_MX_CC_CDIV_TX_MCLK_DIV_CLK_SRC_ID        0x278AA71E
#define LPASS_AON_MX_CC_DEBUG_CLK_ID                       0x27F4C327
#define LPASS_AON_MX_CC_DEBUG_DIV_CLK_SRC_ID               0xF74F3FEF
#define LPASS_AON_MX_CC_DEBUG_MUX_ID                       0x58293A58
#define LPASS_AON_MX_CC_DMIC_DIV_CLK_SRC_ID                0xBEC2D61D
#define LPASS_AON_MX_CC_EXT_IF1_EBIT_CLK_ID                0x2DB81863
#define LPASS_AON_MX_CC_EXT_IF1_IBIT_CLK_ID                0xB62B85E0
#define LPASS_AON_MX_CC_IBI_CLK_ID                         0x13045E7E
#define LPASS_AON_MX_CC_RO_PLL_ID                          0x5E26F2A4
#define LPASS_AON_MX_CC_SLEEP_CLK_ID                       0x85719626
#define LPASS_AON_MX_CC_TLMM_XO_CLK_ID                     0x9BC43B7B
#define LPASS_AON_MX_CC_TX_MCLK_2X_CLK_ID                  0xF4189F9E
#define LPASS_AON_MX_CC_TX_MCLK_CLK_ID                     0x02E39D44
#define LPASS_AON_MX_CC_VA_H_CLK_ID                        0x70E6570D
#define LPASS_AON_MX_CC_VA_MEM0_CLK_ID                     0x3E6AC224
#define LPASS_AON_MX_CC_VA_MEM1_CLK_ID                     0xAAF83C5E
#define LPASS_AON_MX_CC_VA_NIU_CLK_ID                      0x03EC1BC9
#define LPASS_AON_MX_CC_XO_CLK_ID                          0x565A2B67
#define LPASS_AON_MX_CC_XO_DIV16_CLK_ID                    0xD8181004
#define LPASS_AON_MX_CC_XO_DIV16_DIV_CLK_SRC_ID            0x5CE59AC1
#define LPASS_AUDIO_CC_BT_SWR_2X_CLK_ID                    0xCE0809E8
#define LPASS_AUDIO_CC_BT_SWR_CLK_ID                       0xA87BC53E
#define LPASS_AUDIO_CC_BUS_CLK_ID                          0xD3496F44
#define LPASS_AUDIO_CC_BUS_TIMEOUT_CLK_ID                  0xBF4D6430
#define LPASS_AUDIO_CC_CDIV_BT_SWR_DIV_CLK_SRC_ID          0x28FBE1F6
#define LPASS_AUDIO_CC_CDIV_RX_MCLK_DIV_CLK_SRC_ID         0x20813CB7
#define LPASS_AUDIO_CC_CDIV_WSA_MCLK_DIV_CLK_SRC_ID        0xE5F3372B
#define LPASS_AUDIO_CC_CODEC_MEM0_CLK_ID                   0xD18F5466
#define LPASS_AUDIO_CC_CODEC_MEM1_CLK_ID                   0x1E63A7D1
#define LPASS_AUDIO_CC_CODEC_MEM2_CLK_ID                   0x08844E76
#define LPASS_AUDIO_CC_CODEC_MEM3_CLK_ID                   0x5BA30579
#define LPASS_AUDIO_CC_CODEC_MEM4_CLK_ID                   0x08FE26DC
#define LPASS_AUDIO_CC_CODEC_MEM_CLK_ID                    0xD0ADA611
#define LPASS_AUDIO_CC_DEBUG_CLK_ID                        0x4C352779
#define LPASS_AUDIO_CC_DEBUG_MUX_ID                        0x364D702C
#define LPASS_AUDIO_CC_DIG_PLL_ID                          0xBC7CCF07
#define LPASS_AUDIO_CC_EXT_IF1_EBIT_CLK_ID                 0x84F2A19E
#define LPASS_AUDIO_CC_EXT_IF1_IBIT_CLK_ID                 0x013E846E
#define LPASS_AUDIO_CC_EXT_IF2_EBIT_CLK_ID                 0xA56749A0
#define LPASS_AUDIO_CC_EXT_IF2_IBIT_CLK_ID                 0xDDE0F3BF
#define LPASS_AUDIO_CC_EXT_IF4_EBIT_CLK_ID                 0x930996F8
#define LPASS_AUDIO_CC_EXT_IF4_IBIT_CLK_ID                 0xE40B0744
#define LPASS_AUDIO_CC_EXT_IF5_EBIT_CLK_ID                 0x302BA9ED
#define LPASS_AUDIO_CC_EXT_IF5_IBIT_CLK_ID                 0x5CC89347
#define LPASS_AUDIO_CC_EXT_MCLK0_CLK_ID                    0x7CE73EA4
#define LPASS_AUDIO_CC_EXT_MCLK1_CLK_ID                    0xA1FE34EF
#define LPASS_AUDIO_CC_LPAIF_PCMOE_CLK_ID                  0xD6A514ED
#define LPASS_AUDIO_CC_PLL_ID                              0x035D0E6D
#define LPASS_AUDIO_CC_PLL_OUT_EVEN_DIV_CLK_SRC_ID         0x42C5C39B
#define LPASS_AUDIO_CC_RX_MCLK_2X_CLK_ID                   0xF3382AD1
#define LPASS_AUDIO_CC_RX_MCLK_CLK_ID                      0x93BBA610
#define LPASS_AUDIO_CC_RX_MCLK_MCLK2_2X_CLK_ID             0xE889B967
#define LPASS_AUDIO_CC_SAMPLING_CLK_ID                     0x3C011E5D
#define LPASS_AUDIO_CC_SLIMBUS_CLK_ID                      0x173A1689
#define LPASS_AUDIO_CC_SLIMBUS_CORE_CLK_ID                 0x0F69B478
#define LPASS_AUDIO_CC_TX_MCLK_2X_RX_CLK_ID                0xEB8ABAD3
#define LPASS_AUDIO_CC_TX_MCLK_2X_WSA2_CLK_ID              0x5C4FD357
#define LPASS_AUDIO_CC_TX_MCLK_2X_WSA_CLK_ID               0xB4069B23
#define LPASS_AUDIO_CC_TX_MCLK_RX_CLK_ID                   0x027F27B9
#define LPASS_AUDIO_CC_TX_MCLK_WSA2_CLK_ID                 0x56E0721A
#define LPASS_AUDIO_CC_TX_MCLK_WSA_CLK_ID                  0x9DB6DD20
#define LPASS_AUDIO_CC_VA_TX_MCLK_MUX_CLK_ID               0xB48D67C4
#define LPASS_AUDIO_CC_WSA2_MCLK_2X_CLK_ID                 0x0A624C7B
#define LPASS_AUDIO_CC_WSA2_MCLK_BIT_SRC_CLK_ID            0x34BDE104
#define LPASS_AUDIO_CC_WSA2_MCLK_CLK_ID                    0xF3C6E63E
#define LPASS_AUDIO_CC_WSA_MCLK_2X_CLK_ID                  0xA1253E54
#define LPASS_AUDIO_CC_WSA_MCLK_BIT_SRC_CLK_ID             0x68A8FE27
#define LPASS_AUDIO_CC_WSA_MCLK_CLK_ID                     0xB9EF34B0
#define LPASS_AUDIO_CC_XO_CLK_ID                           0x80646148
#define LPASS_AUDIO_CC_XO_DIV16_DIV_CLK_SRC_ID             0x93E2E513
#define LPASS_AUDIO_CC_XPU2_CLIENT_CLK_ID                  0x9264623E
#define LPASS_CORE_CC_AVSYNC_ATIME_CLK_ID                  0xD447F38D
#define LPASS_CORE_CC_AVSYNC_STC_CLK_ID                    0x40C30AF7
#define LPASS_CORE_CC_BUS_TIMEOUT_CORE_CLK_ID              0x83C308DE
#define LPASS_CORE_CC_CORE_CLK_ID                          0x8B7F50B8
#define LPASS_CORE_CC_DEBUG_CLK_ID                         0xFD81A5BB
#define LPASS_CORE_CC_DEBUG_DIV_CLK_SRC_ID                 0xC99E5280
#define LPASS_CORE_CC_DEBUG_MUX_ID                         0x7E878FE1
#define LPASS_CORE_CC_DIG_PLL_ID                           0x00C166C0
#define LPASS_CORE_CC_DIG_PLL_OUT_MAIN_DIV_CLK_SRC_ID      0xD1338C70
#define LPASS_CORE_CC_EXT_IF0_EBIT_CLK_ID                  0xD4F39B70
#define LPASS_CORE_CC_EXT_IF0_IBIT_CLK_ID                  0x9762A104
#define LPASS_CORE_CC_EXT_IF1_EBIT_CLK_ID                  0xD7C4896B
#define LPASS_CORE_CC_EXT_IF1_IBIT_CLK_ID                  0xB8BE19DD
#define LPASS_CORE_CC_EXT_IF2_EBIT_CLK_ID                  0x83A931CA
#define LPASS_CORE_CC_EXT_IF2_IBIT_CLK_ID                  0xFA43802A
#define LPASS_CORE_CC_EXT_MCLK0_CLK_ID                     0x81F35FD9
#define LPASS_CORE_CC_EXT_MCLK1_CLK_ID                     0x64985E0E
#define LPASS_CORE_CC_HW_AF_CLK_ID                         0x44640448
#define LPASS_CORE_CC_HW_AF_NOC_CLK_ID                     0xBEA5796B
#define LPASS_CORE_CC_LPASS_CORE_HM_GDSC_ID                0xE74DBC9C
#define LPASS_CORE_CC_LPM_CORE_CLK_ID                      0x24BC85F3
#define LPASS_CORE_CC_LPM_MEM0_CORE_CLK_ID                 0x650C323C
#define LPASS_CORE_CC_PCMOE_CLK_ID                         0xBB176B94
#define LPASS_CORE_CC_PLL_TEST_CLK_ID                      0x0E8C7B5B
#define LPASS_CORE_CC_PLL_TEST_DIV_CLK_SRC_ID              0x205F433B
#define LPASS_CORE_CC_Q6SS_AXIM2_CORE_CLK_ID               0xCF049200
#define LPASS_CORE_CC_RESAMPLER_CLK_ID                     0x8EB698E8
#define LPASS_CORE_CC_SAMPLING_CLK_ID                      0x0098B61F
#define LPASS_CORE_CC_SLEEP_CLK_ID                         0x1EE7054B
#define LPASS_CORE_CC_SYSNOC_MPORT_CORE_CLK_ID             0x396554A8
#define LPASS_CORE_CC_SYSNOC_SWAY_CORE_CLK_ID              0xACF7C9ED
#define LPASS_CORE_CC_XO_CLK_ID                            0x86D82846
#define LPASS_CORE_CC_XO_DIV16_DIV_CLK_SRC_ID              0x51591264
#define LPASS_LPASS_CORE_HM_BCR_ID                         0xFA89C3BA
#define LPASS_LPI_TCM_256KB_BLOCK0_CLK_ID                  0xC30C7589
#define LPASS_LPI_TCM_256KB_BLOCK10_CLK_ID                 0x090E53A8
#define LPASS_LPI_TCM_256KB_BLOCK11_CLK_ID                 0x84188364
#define LPASS_LPI_TCM_256KB_BLOCK1_CLK_ID                  0xE7362670
#define LPASS_LPI_TCM_256KB_BLOCK2_CLK_ID                  0x8CF6C9A2
#define LPASS_LPI_TCM_256KB_BLOCK3_CLK_ID                  0xFCAE8B7C
#define LPASS_LPI_TCM_256KB_BLOCK4_CLK_ID                  0x055547BE
#define LPASS_LPI_TCM_256KB_BLOCK5_CLK_ID                  0x293D22CD
#define LPASS_LPI_TCM_256KB_BLOCK6_CLK_ID                  0x565522DC
#define LPASS_LPI_TCM_256KB_BLOCK7_CLK_ID                  0x7415E33A
#define LPASS_LPI_TCM_256KB_BLOCK8_CLK_ID                  0x9CD14666
#define LPASS_LPI_TCM_256KB_BLOCK9_CLK_ID                  0x31B5EA6C
#define LPASS_LPI_TCM_AXIS_HS_CLK_ID                       0xBD27FA14
#define LPASS_Q6_CORE_CLK_ID                               0x95352CDB
#define LPASS_Q6_SPDM_CORE_DIV_CLK_ID                      0xF78332E0
#define LPASS_Q6_SPDM_CORE_DIV_CLK_SRC_ID                  0x816BEEE2
#define LPASS_QDSP6SS_PLL_ID                               0x65447614
#define LPASS_TOP_CC_DEBUG_MUX_ID                          0x7AD0326A
#define XO_38P4_ID                                         0x24A27735

#endif
