#pragma once
/** ============================================================================
 * @file
 *
 * @brief Synchronous services provided by the Framework.
 *
 * @copyright Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * All rights reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 *
 * ===========================================================================*/

/*==============================================================================
  Include Files
  ============================================================================*/

#include <stdint.h>

/*==============================================================================
  Type Definitions
  ============================================================================*/

/**
 * @brief Enumeration of Services provided by the Framework.
 * Some of these are core services which will be provided in every
 * variation of the Framework.  Others are target or version specific.
 * Clients must query to determine if a particular service is available
 * on the system.
 *
 */
typedef enum sns_service_type
{
  SNS_STREAM_SERVICE,         /*!< This service provides stream processing
                               *   capabilities.
                               */
  SNS_ATTRIBUTE_SERVICE,      /*!< This service manages attributes associated
                               *   with sensors. */
  SNS_DYNAMIC_BUFFER_SERVICE, /*!< This service offers dynamic buffer
                               *   management. */
  SNS_EVENT_SERVICE,          /*!< This service handles events generated by
                               *   sensors.
                               */
  SNS_POWER_RAIL_SERVICE,     /*!< This service manages power rails. */
  SNS_DIAG_SERVICE,           /*!< This service provides diagnostic
                               *   information. */
  SNS_SYNC_COM_PORT_SERVICE,  /*!< This service facilitates synchronous
                               *   communication over serial ports.
                               */
  SNS_GPIO_SERVICE,           /*!< This service controls General Purpose
                               *   Input/Output (GPIO) pins.
                               */
  SNS_ISLAND_SERVICE,         /*!< This service manages Island sections of the
                               *   system.
                               */
  SNS_REGISTRATION_SERVICE,   /*!< This service handles sensor registrations. */
  SNS_POWER_MGR_SERVICE,      /*!< This service manages power management
                               *   policies.
                               */
  SNS_MEMORY_SERVICE,         /*!< This service provides memory management
                               *   functionalities.
                               */
  SNS_FILE_SERVICE,           /*!< This service handles file operations. */
  SNS_SFE_SERVICE,            /*!< This service handles SFE operations. */
  SNS_SERVICE_TYPE_LENGTH     /*!< A placeholder member indicating the number of
                               *   service types defined in this enumeration. */
} sns_service_type;

/**
 * @brief Service attributes.  New fields cannot be added without a Framework
 * major revision.
 *
 */
typedef struct sns_service
{
  /**
   * @brief Version number of this service; incremented only when new
   * functionality is added to the service.  Backward compatibility shall be
   * maintained for all services.
   *
   */
  uint16_t version;
  sns_service_type type; /*!< Type of serive. */
} sns_service;
