#pragma once
/** ===========================================================================
 * @file
 *
 * @brief An output generated by a Sensor.  The Event may contain multiple
 * logical sensor samples.  The Framework will ensure samples can be
 * fed into the client individually.
 *
 * @copyright Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 *
 * ===========================================================================*/

/*==============================================================================
  Include Files
  ============================================================================*/

#include <inttypes.h>
#include "sns_time.h"

/*==============================================================================
  Type Definitions
  ============================================================================*/

/**
 * @brief Structure for an event generated by a sensor.
 *
 */
typedef struct sns_sensor_event
{
  sns_time timestamp;   /*!< Timestamp of the event. */
  uint32_t message_id;  /*!< Sensor event Message ID. */
  uint32_t event_len;   /*!< Length of the event. */
  uint64_t event[1];    /*!< Sensor event data. */ 
} sns_sensor_event;
