#ifndef _CSR_SYNERGY_BT_CONFIG_GLOBAL_H
#define _CSR_SYNERGY_BT_CONFIG_GLOBAL_H
/******************************************************************************
 Copyright (c) 2011-2025 Qualcomm Technologies International, Ltd.
 All Rights Reserved.
 Qualcomm Technologies International, Ltd. Confidential and Proprietary.

REVISION:      $Revision: #36 $
******************************************************************************/

#ifdef __cplusplus
    extern "C" {
#endif

/* BlueStack on host */
#define BUILD_FOR_HOST 
#undef DM_ACL_DUMP_DEBUG
#undef INSTALL_VM_MODULE
#ifndef INSTALL_DM_POWERSTATES_MODULE
#define INSTALL_DM_POWERSTATES_MODULE
#endif
#undef INSTALL_L2CAP_CRC
#undef INSTALL_L2CAP_ROUTER_SUPPORT
#undef L2CAP_HCI_DATA_CREDIT_CHECKS
#undef L2CAP_HCI_DATA_CREDIT_CHECKS_PANIC
#undef L2CAP_HCI_DATA_CREDIT_SLOW_CHECKS

/* ---------- General Blue Stack flags ---------- */
#ifdef CSR_BT_BLUE_STACK_DEBUG
#define SM_DEBUG_PAIRING_SANITY
#define DM_ACL_DEBUG
#define INSTALL_L2CAP_DEBUG
#endif

#ifndef CSR_QCA_QVSC
#define INSTALL_VSC
#endif

#ifndef INSTALL_MULTIPLE_EXTENDED_FEATURES_PAGES
#define INSTALL_MULTIPLE_EXTENDED_FEATURES_PAGES
#endif

#ifndef INSTALL_BREDR_SECURE_CONNECTIONS
#define INSTALL_BREDR_SECURE_CONNECTIONS
#endif

#ifndef INSTALL_BREDR_PING
#define INSTALL_BREDR_PING
#endif

#ifndef INSTALL_SC_ESCO_PARAMS_REWRITE
#define INSTALL_SC_ESCO_PARAMS_REWRITE
#endif

#ifdef CSR_BT_SC_ONLY_MODE_ENABLE
#define INSTALL_GAP_SC_ONLY_MODE
#endif

/* L2CAP mandatory settings */
#define INSTALL_L2CAP_MODULE
#define INSTALL_L2CAP_ENHANCED_SUPPORT
#define USB_ACL_DATA_FIX

#define INSTALL_L2CAP_QOS_SUPPORT 

/* SDP mandatory settings */
#define INSTALL_SDP_MODULE
#undef INSTALL_SDP_STATIC_SERVICE_RECORD_SUPPORT
#define INSTALL_CMN_ENHANCED_SDP_FEATURE

/* SC mandatory settings */
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ACL_CONNECTION


#ifndef CSR_AMP_ENABLE
#define DISABLE_AMP_FSM_SUPPORT /* Used only by AMP */
#if !defined(CSR_BT_LE_ENABLE) && !defined(INSTALL_L2CAP_FIXED_CHANNEL_BASE_SUPPORT)
#define DISABLE_L2CAP_FIXED_CHANNEL_FSM_SUPPORT /* Used by LE, AMP */
#endif
#endif

/* ---------- Profile dependent flags ---------- */
#define EXCLUDE_CSR_BT_AMPM_MODULE


/* BLE mandatory settings */
#ifdef CSR_BT_LE_ENABLE
#define CSR_BT_INSTALL_L2CAP_MODULE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_BLUECORE_INITIALIZED
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ACL_CONNECTION
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LOCAL_NAME_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LOW_ENERGY
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LE_OWN_ADDR_TYPE_CHANGE
#define BUILD_FOR_HOST_FOR_ENCRYPTION_ATT_RACE
#define BUILD_FOR_HOST_FOR_ENCRYPTION_SMP_RACE
#define INSTALL_ULP
#if (defined(CSR_BT_INSTALL_EXTENDED_ADVERTISING) || \
    defined(CSR_BT_INSTALL_EXTENDED_SCANNING) || \
    defined(CSR_BT_INSTALL_PERIODIC_ADVERTISING) || \
    defined(CSR_BT_INSTALL_PERIODIC_SCANNING))
#define ENABLE_ADV_REPORTING_WITH_MBLK
#define GAM_IOP_USE_SECONDARY_ADV_CH
#define INSTALL_ADVERTISING_EXTENSIONS
#define INSTALL_CM_EXT_ADV_SET_PARAM_V2
#endif /* End of  CSR_BT_INSTALL_EXTENDED_ADVERTISING || CSR_BT_INSTALL_EXTENDED_SCANNING ||
        * CSR_BT_INSTALL_PERIODIC_ADVERTISING || CSR_BT_INSTALL_PERIODIC_SCANNING */

#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LE_SUBRATE_CHANGE
#define INSTALL_LE_ENHANCED_CONN_UPDATE_SUPPORT

#define INSTALL_ATT_MODULE
#ifdef CSR_BT_GATT_INSTALL_EATT
#define INSTALL_EATT
#define INSTALL_L2CAP_ECBFC
#define INSTALL_L2CAP_LECOC_CB
#endif /* CSR_BT_GATT_INSTALL_EATT */
#define INSTALL_ATT_BREDR
#define INSTALL_L2CAP_FIXED_CHANNEL_BASE_SUPPORT
#define INSTALL_L2CAP_FIXED_CHANNEL_SUPPORT
#ifdef CSR_BT_INSTALL_DLE_SUPPORT
#define INSTALL_DLE
#endif /* CSR_BT_INSTALL_DLE_SUPPORT */
#define INSTALL_SM_MODULE
#define INSTALL_SM_PRIVACY_1P2
#define INSTALL_DM_CONNECTIONLESS_FSM
#define INSTALL_DM_CONNECTIONLESS_PARAMETERS_ENHANCEMENT
#define INSTALL_DM_CONNECTIONLESS_WHITE_LIST_ENHANCEMENT
#define INSTALL_SM_PRIVACY_1P2_DUMMY_RL
#ifdef CSR_BT_INSTALL_LESC_SUPPORT
#define INSTALL_SM_LE_SECURE_CONNECTIONS
#define INSTALL_LE_PING
#define INSTALL_KEYPRESS_NOTIFICATION
#endif
#ifdef CSR_BT_INSTALL_CTKD_SUPPORT
#ifndef CSR_BT_DISABLE_H7_CTKD
#define INSTALL_SM_LE_SECURE_CONNECTIONS_H7
#endif
#else
#define DISABLE_SM_CROSS_TRNSPT_KEY_DERIVATION
#endif
#define SM_HAS_FUNCTION_FOR_RAND
#define INSTALL_CPRP
#define INSTALL_SIFE
#ifndef EXCLUDE_CSR_BT_GATT_MODULE_OPTIONAL
#define CSR_BT_INSTALL_GATT_PARAM_CONNECTION
#endif
#ifndef EXCLUDE_CSR_BT_THERM_SRV_MODULE
#endif

#ifndef CSR_BT_GATT_CLIENT_UTIL_TRACK_ENCRYPTION
#define CSR_BT_GATT_CLIENT_UTIL_TRACK_ENCRYPTION
#endif

#else /* CSR_BT_LE_ENABLE */
#define CSR_BT_EXCLUDE_SET_BLE_CONNECTION_PARAMETERS
#define CSR_BT_EXCLUDE_SM_SECURITY
#define EXCLUDE_CSR_BT_ATT_MODULE
#define EXCLUDE_CSR_BT_GATT_MODULE
#define EXCLUDE_CSR_BT_GATT_PRIVATE_MODULE
#define EXCLUDE_CSR_BT_THERM_SRV_MODULE
#define EXCLUDE_CSR_BT_PROX_SRV_MODULE
#endif /* CSR_BT_LE_ENABLE */


#if defined (CSR_TARGET_PRODUCT_WEARABLE)
#define CSR_BT_INSTALL_RFC_MODULE
#endif


#ifndef EXCLUDE_CSR_BT_MCAP_MODULE 
#define CSR_BT_INSTALL_L2CAP_MODULE
#else
#define EXCLUDE_CSR_BT_MCAP_PRIVATE_MODULE 
#endif



#ifndef CSR_BT_INSTALL_CM_HANDLE_REGISTER
#define CSR_BT_INSTALL_CM_HANDLE_REGISTER
#endif

#if defined(CSR_BT_INSTALL_SC_DEBUG_MODE) || defined(CSR_BT_INSTALL_SC_CONFIG_MASK)
#define CSR_BT_INSTALL_CM_SC_MODE_CONFIG
#endif

#ifdef CSR_BT_INSTALL_SC_OOB
#define CSR_BT_INSTALL_CM_OOB
#endif

/* If application does not write class of device, update it autonomously */
#ifndef CSR_BT_INSTALL_CM_WRITE_COD
#define CSR_BT_INSTALL_CM_AUTO_UPDATE_COD
#endif

#ifndef CSR_BT_INSTALL_CM_OOB
#define CSR_BT_EXCLUDE_SM_READ_LOCAL_OOB_DATA
#endif

#ifndef CSR_BT_INSTALL_CM_READ_LOCAL_NAME
#define EXCLUDE_CSR_BT_CM_READ_LOCAL_NAME_REQ
#define EXCLUDE_CSR_BT_CM_READ_LOCAL_NAME_CFM
#endif

#ifdef CSR_BT_INSTALL_INTERNAL_APP_DEPENDENCIES
/* If this flag is set, the code needed by internal 
   CSR-applications will be included. */
#define CSR_BT_INSTALL_CM_WRITE_COD /* Used by GAP demo app */
#define CSR_BT_INSTALL_CM_PRI_CONNECT_EXT /* Used by RFC test demo app */



/* Used by SC demo app */
#define CSR_BT_INSTALL_SC_SET_EVENT_MASK
#define CSR_BT_INSTALL_SC_SET_IO_CAPABILITY
#define CSR_BT_INSTALL_SC_SET_AUTH_REQUIREMENTS
#define CSR_BT_INSTALL_SC_LE_KEY_DISTRIBUTION
#ifndef CSR_TARGET_PRODUCT_WEARABLE
#define CSR_BT_INSTALL_SC_SECURITY_MODE
#endif
#define CSR_BT_INSTALL_SC_EVENT_MASK_SUBSCRIBE_ADDRESS_MAPPED_IND
#define CSR_BT_INSTALL_UTIL_UCS2

#endif /* CSR_BT_INSTALL_INTERNAL_APP_DEPENDENCIES */

#ifdef CSR_BT_INSTALL_INTERNAL_TEST_DEPENDENCIES
/* If this flag is set, the code needed by internal
   CSR tests will be included. */

#define CSR_BT_INSTALL_CM_READ_SCAN_EANBLE /* Used by several tester/tester groups */
#define CSR_BT_INSTALL_CM_LINK_POLICY /* Used by 1 tester/tester test case but several CM module tests */
#define CSR_BT_INSTALL_CM_READ_CLOCK /* Used by 1 tester/tester test case and profile_managers_development/test_app/app_files/csr_bt_test_app_mcap.c */
#define CSR_BT_INSTALL_CM_ROLE_SWITCH_CONFIG /* Used by 1 tester/tester test case and 1 CM module test case */
#define CSR_BT_INSTALL_CM_PRI_ALWAYS_SUPPORT_MASTER_ROLE /* Used by a few cm tester/tester test cases and throughput */
#define CSR_BT_INSTALL_CM_PRI_CANCEL_RFC_EXTENDED_SEARCH /* Used by a few tester/tester test cases */
#define CSR_BT_INSTALL_CM_PRI_SDC /* Used by a few tester/tester test cases and 1 CM module test case */
#define CSR_BT_INSTALL_CM_PRI_L2CA_CONNECT_CONFTAB /* Used by a few tester/tester test cases */
#ifndef EXCLUDE_CSR_BT_SC_MODULE
#define CSR_BT_INSTALL_SC_SECURITY_MODE /* This is needed to run the sc-group in tester, since all test cases sends the request. */
#endif
#define CSR_BT_INSTALL_OPTIONAL_UTIL /* Used by more or less all tester/tester test cases */
#define CSR_BT_INSTALL_CM_READ_RSSI /* Used by the generic test step testCaseWaitAclClosedInd() */

/* Low risk */
#define CSR_BT_INSTALL_SD_SEARCH_CONFIG
#define CSR_BT_INSTALL_SD_MEMORY_CONFIG

#define CSR_BT_INSTALL_HF_CONFIG_AUDIO
#define CSR_BT_INSTALL_HFG_CONFIG_AUDIO

#define CSR_BT_INSTALL_SC_SET_EVENT_MASK
#define CSR_BT_INSTALL_SC_SET_IO_CAPABILITY
#define CSR_BT_INSTALL_SC_SET_AUTH_REQUIREMENTS
#define CSR_BT_INSTALL_SC_LE_KEY_DISTRIBUTION
#define CSR_BT_INSTALL_SC_EVENT_MASK_SUBSCRIBE_ADDRESS_MAPPED_IND
#define CSR_BT_INSTALL_UTIL_UCS2

#else /* CSR_BT_INSTALL_INTERNAL_TEST_DEPENDENCIES */
/* Used for spec. test */
#define CSR_BT_EXCLUDE_HCI_CHANGE_CONN_LINK_KEY
#define CSR_BT_EXCLUDE_HCI_HOLD_MODE

#endif /* CSR_BT_INSTALL_INTERNAL_TEST_DEPENDENCIES */

#ifndef EXCLUDE_CSR_BT_DUT_MODULE
#define CSR_BT_INSTALL_CM_DUT_MODE
#else
#define CSR_BT_EXCLUDE_HCI_ENABLE_DUT_MODE
#endif


/* Convert to low-level EXCLUDE_FLAG 
TODO: CSR_BT_BT_VERSION is defined in csr_bt_usr_config.h, but it cannot be included
      in this file, since it includes other headers, which depend on this file... 
      One solution would be to move the include of the file to the bottom of this file
#ifndef CSR_BT_INSTALL_CM_READ_LOCAL_NAME
#if CSR_BT_BT_VERSION < CSR_BT_BLUETOOTH_VERSION_2P1
#define CSR_BT_EXCLUDE_HCI_READ_LOCAL_NAME
#endif
#endif
#if CSR_BT_BT_VERSION < CSR_BT_BLUETOOTH_VERSION_2P1
#define CSR_BT_EXCLUDE_HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_DATA
#endif
*/

/* ---------- Cross Profile dependent flags ---------- */

#ifndef EXCLUDE_CSR_EXCEPTION_HANDLER_MODULE
#define CSR_BT_INSTALL_OBEX_ERROR_CHECK
#endif


/* ---------- Ensure we have backwards compatibility ---------- */
#ifndef EXCLUDE_CSR_BT_OPTIONAL_UTILS 
#define CSR_BT_INSTALL_UTIL_UCS2
#define CSR_BT_INSTALL_OPTIONAL_UTIL
#define CSR_BT_INSTALL_OBEX_UTIL_XML
#define CSR_BT_INSTALL_OBEX_UTIL_SET_SERVICE_HANDLE_RES
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_NON_CONNECTABLE
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#else
#if defined(EXCLUDE_CSR_BT_BSL_MODULE) && defined(EXCLUDE_CSR_BT_DUNC_MODULE) && !defined(CSR_BT_INSTALL_INTERNAL_TEST_DEPENDENCIES) && !defined(CSR_BT_INSTALL_INTERNAL_APP_DEPENDENCIES)
#define EXCLUDE_CSR_BT_UDP_MODULE
#define EXCLUDE_CSR_BT_LSL_MODULE
#define EXCLUDE_CSR_BT_IP_MODULE
#define EXCLUDE_CSR_BT_ICMP_MODULE
#define EXCLUDE_CSR_BT_DHCP_MODULE
#define EXCLUDE_CSR_BT_PPP_MODULE
#endif
#endif

/* ---------- Test functionality ---------- */
#ifndef EXCLUDE_CSR_BT_TPT_MODULE
#define CSR_BT_INSTALL_AV_SET_QOS_INTERVAL
/* REQ SPP */
#endif

/* ---------- Resolve install-flags dependencies ---------- */
#ifdef CSR_BT_INSTALL_OBEX_CLI_GET
#define CSR_BT_INSTALL_OBEX_UTIL_BODY_OFFSET 
#endif

#ifndef INSTALL_CSR_BT_SD_SERVICE_RECORD_MODULE
#ifndef EXCLUDE_CSR_BT_SD_SERVICE_RECORD_MODULE
#define EXCLUDE_CSR_BT_SD_SERVICE_RECORD_MODULE
#endif
#endif

#ifdef CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_L2CAP_MODULE
#endif

/* ---------- Convert install-flags to legacy exclude-flags ---------- */

#ifndef CSR_BT_INSTALL_L2CAP_MODULE
#undef EXCLUDE_CSR_BT_L2CA_MODULE
#define EXCLUDE_CSR_BT_L2CA_MODULE
#endif

#ifndef CSR_BT_INSTALL_RFC_MODULE
#undef EXCLUDE_CSR_BT_RFC_MODULE
#define EXCLUDE_CSR_BT_RFC_MODULE
#endif

#ifndef CSR_BT_INSTALL_BSL_MODULE
#undef EXCLUDE_CSR_BT_BNEP_MODULE 
#define EXCLUDE_CSR_BT_BNEP_MODULE 
#endif

#ifndef CSR_BT_INSTALL_MDER_MODULE
#undef EXCLUDE_CSR_BT_MDER_MODULE 
#define EXCLUDE_CSR_BT_MDER_MODULE 
#endif

/* DM_SYNC (SCO) mandatory settings */
#ifndef CSR_BT_INSTALL_SCO_MODULE
#undef EXCLUDE_CSR_BT_SCO_MODULE
#define EXCLUDE_CSR_BT_SCO_MODULE
#undef INSTALL_DM_SYNC_MODULE
#undef CSR_BT_MAX_NUM_SCO_CONNS /* This will not work, as csr_bt_user_config.h is included after this file is included */
#define CSR_BT_EXCLUDE_SYNC_CONNECT
#define CSR_BT_EXCLUDE_SYNC_DISCONNECT
#define CSR_BT_EXCLUDE_SYNC_REGISTER
#define CSR_BT_EXCLUDE_SYNC_RENEGOTIATE
#define CSR_BT_EXCLUDE_SYNC_UNREGISTER
#else
#define INSTALL_DM_SYNC_MODULE
#endif

/* DM mandatory settings */
#ifndef INSTALL_BUILD_FOR_HOST_DM_ACL_CON_START_IND
#define INSTALL_BUILD_FOR_HOST_DM_ACL_CON_START_IND
#endif

#ifndef BUILD_FOR_HOST_OLD_LINK_KEY_API
#define BUILD_FOR_HOST_OLD_LINK_KEY_API
#endif

/* RFCOMM mandatory settings */
#ifndef EXCLUDE_CSR_BT_RFC_MODULE
#undef INSTALL_RFCOMM_MODULE
#define INSTALL_RFCOMM_MODULE
#define RFCOMM_MULTI_THREAD
#endif /* EXCLUDE_CSR_BT_RFC_MODULE */


#ifdef INSTALL_IBFP
#undef CSR_IBFP_H4I_SUPPORT
#define CSR_IBFP_H4I_SUPPORT

#undef CSR_H4I_ENABLE_PATCH
#define CSR_H4I_ENABLE_PATCH

#undef CSR_BT_INSTALL_CHANGE_ACL_PACKET_TYPE
#define CSR_BT_INSTALL_CHANGE_ACL_PACKET_TYPE

#undef INSTALL_BUILD_FOR_HOST_NO_OVERRIDE_HCI_CMD_FC
#define INSTALL_BUILD_FOR_HOST_NO_OVERRIDE_HCI_CMD_FC
#endif


#ifdef CSR_USE_QCA_CHIP
#ifdef CSR_BT_LE_ENABLE
#undef SUPPORT_SEPARATE_LE_BUFFERS 
#define SUPPORT_SEPARATE_LE_BUFFERS
#endif
#endif

/* Exclude converter functions for specific primitives */
#ifndef CSR_BT_INSTALL_SC_SET_EVENT_MASK
#define EXCLUDE_CSR_BT_SC_SET_EVENT_MASK_REQ
#endif

#ifndef CSR_BT_INSTALL_SC_SET_IO_CAPABILITY
#define EXCLUDE_CSR_BT_SC_SET_IO_CAPABILITY_REQ
#endif

#ifndef CSR_BT_INSTALL_SC_SET_AUTH_REQUIREMENTS
#define EXCLUDE_CSR_BT_SC_SET_AUTH_REQUIREMENTS_REQ
#endif

#ifndef CSR_BT_INSTALL_SC_MODE
#define EXCLUDE_CSR_BT_SC_MODE_REQ
#define EXCLUDE_CSR_BT_SC_MODE_IND
#endif

#ifndef CSR_BT_INSTALL_SC_LE_KEY_DISTRIBUTION
#define EXCLUDE_CSR_BT_SC_LE_KEY_DISTRIBUTION_REQ
#endif

#ifndef CSR_BT_INSTALL_SC_EVENT_MASK_SUBSCRIBE_ADDRESS_MAPPED_IND
#define CSR_BT_INSTALL_SC_EVENT_MASK_SUBSCRIBE_ADDRESS_MAPPED_IND
#endif

#ifndef CSR_BT_INSTALL_AV_SET_QOS_INTERVAL
#define EXCLUDE_CSR_BT_AV_SET_QOS_INTERVAL_REQ
#endif

#ifndef CSR_BT_INSTALL_SD_SEARCH_CONFIG
#define EXCLUDE_CSR_BT_SD_SEARCH_CONFIG_REQ
#define EXCLUDE_CSR_BT_SD_SEARCH_CONFIG_CFM
#endif

#ifndef CSR_BT_INSTALL_CM_WRITE_VOICE_SETTINGS
#define EXCLUDE_CSR_BT_CM_WRITE_VOICE_SETTINGS_REQ
#define EXCLUDE_CSR_BT_CM_WRITE_VOICE_SETTINGS_CFM
#endif

#ifndef CSR_BT_INSTALL_HF_CONFIG_AUDIO
#define EXCLUDE_CSR_BT_HF_CONFIG_AUDIO_REQ
#define EXCLUDE_CSR_BT_HF_CONFIG_AUDIO_CFM
#endif

#ifndef CSR_BT_INSTALL_HFG_CONFIG_AUDIO
#define EXCLUDE_CSR_BT_HFG_CONFIG_AUDIO_REQ
#endif
#ifndef CSR_BT_INSTALL_HFG_CONFIG_SINGLE_ATCMD
#define EXCLUDE_CSR_BT_HFG_CONFIG_SINGLE_ATCMD_REQ
#define EXCLUDE_CSR_BT_HFG_CONFIG_SINGLE_ATCMD_CFM
#endif
#ifndef CSR_BT_INSTALL_HFG_CONFIG_ATCMD_HANDLING
#define EXCLUDE_CSR_BT_HFG_CONFIG_ATCMD_HANDLING_REQ
#define EXCLUDE_CSR_BT_HFG_CONFIG_ATCMD_HANDLING_CFM
#endif

#ifndef CSR_BT_INSTALL_GATT_PARAM_CONNECTION
#define EXCLUDE_CSR_BT_GATT_PARAM_CONNECTION_REQ
#define EXCLUDE_CSR_BT_GATT_PARAM_CONNECTION_CFM
#endif

#ifndef CSR_BT_INSTALL_AVRCP_CT_13_AND_HIGHER
#define EXCLUDE_CSR_BT_AVRCP_CT_INFORM_DISP_CHARSET_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_REGISTER_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_ATT_ID_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_VAL_ID_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_ATT_TXT_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_VAL_TXT_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_ATT_TXT_RES
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_VAL_TXT_RES
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_CURRENT_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_SET_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_PLAY_STATUS_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_ATTRIBUTES_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_ATTRIBUTES_RES
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_FOLDER_ITEMS_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PLAY_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_SEARCH_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_CHANGE_PATH_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_VOLUME_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_ADDRESSED_PLAYER_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_BROWSED_PLAYER_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_ADD_TO_NOW_PLAYING_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_INFORM_BATTERY_STATUS_REQ

#define EXCLUDE_CSR_BT_AVRCP_CT_INFORM_DISP_CHARSET_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_REGISTER_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_PLAY_STATUS_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_ATT_ID_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_VAL_ID_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_ATT_TXT_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_VAL_TXT_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_CURRENT_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_SET_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_FOLDER_ITEMS_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PLAY_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_SEARCH_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_ATTRIBUTES_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_CHANGE_PATH_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_VOLUME_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_ADDRESSED_PLAYER_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_BROWSED_PLAYER_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_ADD_TO_NOW_PLAYING_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_INFORM_BATTERY_STATUS_CFM

#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_ATT_TXT_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_VAL_TXT_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_SET_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_UIDS_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_VOLUME_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_BATTERY_STATUS_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_PLAYBACK_POS_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_SYSTEM_STATUS_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_TRACK_CHANGED_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_TRACK_END_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_TRACK_START_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_PLAYBACK_STATUS_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_AVAILABLE_PLAYERS_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_NOW_PLAYING_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_ATTRIBUTES_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_ADDRESSED_PLAYER_IND
#endif
#ifndef CSR_BT_INSTALL_AVRCP_TG_13_AND_HIGHER
#define EXCLUDE_CSR_BT_AVRCP_TG_NOTI_REQ
#define EXCLUDE_CSR_BT_AVRCP_TG_PAS_SET_REQ
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_ADDRESSED_PLAYER_REQ
#define EXCLUDE_CSR_BT_AVRCP_TG_NOTI_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_PLAY_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_SEARCH_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_CHANGE_PATH_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_PAS_SET_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_PAS_CURRENT_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_VOLUME_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_GET_FOLDER_ITEMS_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_GET_ATTRIBUTES_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_GET_PLAY_STATUS_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_ADDRESSED_PLAYER_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_BROWSED_PLAYER_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_ADD_TO_NOW_PLAYING_RES

#define EXCLUDE_CSR_BT_AVRCP_TG_SET_ADDRESSED_PLAYER_CFM
#define EXCLUDE_CSR_BT_AVRCP_TG_NOTI_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_PLAY_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_SEARCH_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_PAS_CURRENT_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_CHANGE_PATH_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_PAS_SET_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_VOLUME_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_GET_FOLDER_ITEMS_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_GET_PLAY_STATUS_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_ADDRESSED_PLAYER_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_BROWSED_PLAYER_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_GET_ATTRIBUTES_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_ADD_TO_NOW_PLAYING_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_INFORM_DISP_CHARSET_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_INFORM_BATTERY_STATUS_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_NOTI_CFM
#define EXCLUDE_CSR_BT_AVRCP_TG_PAS_SET_CFM
#endif

#ifndef INSTALL_ULP
#define CSR_BT_EXCLUDE_BLE_ACCEPT_CONNECTION_PAR_UPDATE
#define CSR_BT_EXCLUDE_BLE_UPDATE_CONNECTION_PARAMETERS
#define CSR_BT_EXCLUDE_HCI_ULP_ADD_DEVICE_TO_WHITE_LIST
#define CSR_BT_EXCLUDE_HCI_ULP_CLEAR_WHITE_LIST
#define CSR_BT_EXCLUDE_HCI_ULP_CREATE_CONNECTION_CANCEL
#define CSR_BT_EXCLUDE_HCI_ULP_ENCRYPT
#define CSR_BT_EXCLUDE_HCI_ULP_RAND
#define CSR_BT_EXCLUDE_HCI_ULP_READ_ADVERTISING_CHANNEL_TX_POWER
#define CSR_BT_EXCLUDE_HCI_ULP_READ_CHANNEL_MAP
#define CSR_BT_EXCLUDE_HCI_ULP_READ_LOCAL_SUPPORTED_FEATURES
#define CSR_BT_EXCLUDE_HCI_ULP_READ_REMOTE_USED_FEATURES
#define CSR_BT_EXCLUDE_HCI_ULP_READ_SUPPORTED_STATES
#define CSR_BT_EXCLUDE_HCI_ULP_READ_WHITE_LIST_SIZE
#define CSR_BT_EXCLUDE_HCI_ULP_RECEIVER_TEST
#define CSR_BT_EXCLUDE_HCI_ULP_REMOVE_DEVICE_FROM_WHITE_LIST
#define CSR_BT_EXCLUDE_HCI_ULP_SET_ADVERTISE_ENABLE
#define CSR_BT_EXCLUDE_HCI_ULP_SET_ADVERTISING_DATA
#define CSR_BT_EXCLUDE_HCI_ULP_SET_ADVERTISING_PARAMETERS
#define CSR_BT_EXCLUDE_HCI_ULP_SET_EVENT_MASK
#define CSR_BT_EXCLUDE_HCI_ULP_SET_HOST_CHANNEL_CLASSIFICATION
#define CSR_BT_EXCLUDE_HCI_ULP_SET_RANDOM_ADDRESS
#define CSR_BT_EXCLUDE_HCI_ULP_SET_SCAN_ENABLE
#define CSR_BT_EXCLUDE_HCI_ULP_SET_SCAN_PARAMETERS
#define CSR_BT_EXCLUDE_HCI_ULP_SET_SCAN_RESPONSE_DATA
#define CSR_BT_EXCLUDE_HCI_ULP_TEST_END
#define CSR_BT_EXCLUDE_HCI_ULP_TRANSMITTER_TEST
#define CSR_BT_EXCLUDE_HCI_ULP_SET_PRIVACY_MODE
#endif

#ifndef INSTALL_AMP_SUPPORT
/* AMP only signals */
#define CSR_BT_EXCLUDE_AMPM_CONNECT
#define CSR_BT_EXCLUDE_AMPM_CONNECT_CHANNEL
#define CSR_BT_EXCLUDE_AMPM_DISCONNECT
#define CSR_BT_EXCLUDE_AMPM_DISCONNECT_CHANNEL
#define CSR_BT_EXCLUDE_AMPM_NUMBER_COMPLETED_DATA_BLOCKS
#define CSR_BT_EXCLUDE_AMPM_READ_BD_ADDR
#define CSR_BT_EXCLUDE_AMPM_READ_DATA_BLOCK_SIZE
#define CSR_BT_EXCLUDE_AMPM_REGISTER
#define CSR_BT_EXCLUDE_AMPM_VERIFY_PHYSICAL_LINK
/* Signals only used for AMP */
#define CSR_BT_EXCLUDE_DATA_FROM_HCI
#endif

#ifndef INSTALL_BD_ADDR_BLACK_LIST_SUPPORT
#define CSR_BT_EXCLUDE_HANDLE_DEVICE_BLACK_LIST
#endif

#ifndef CSR_BT_INSTALL_CM_GET_LINK_QUALITY
#define CSR_BT_EXCLUDE_HCI_GET_LINK_QUALITY
#endif

#ifndef CSR_BT_INSTALL_CM_AFH
#define CSR_BT_EXCLUDE_HCI_READ_AFH_CHANNEL_CLASS_M
#define CSR_BT_EXCLUDE_HCI_READ_AFH_CHANNEL_MAP
#define CSR_BT_EXCLUDE_HCI_SET_AFH_CHANNEL_CLASS
#define CSR_BT_EXCLUDE_HCI_WRITE_AFH_CHANNEL_CLASS_M
#endif

#ifndef CSR_BT_INSTALL_CM_READ_COD
#define CSR_BT_EXCLUDE_HCI_READ_CLASS_OF_DEVICE
#endif

#ifndef CSR_BT_INSTALL_CM_READ_CLOCK
#define CSR_BT_EXCLUDE_HCI_READ_CLOCK
#endif

#ifndef CSR_BT_INSTALL_CM_PRI_IAC
#define CSR_BT_EXCLUDE_HCI_READ_CURRENT_IAC_LAP
#define CSR_BT_EXCLUDE_HCI_READ_NUM_SUPPORTED_IAC
#define CSR_BT_EXCLUDE_HCI_WRITE_CURRENT_IAC_LAP
#endif

/* This requiers the csr_bt_usr_config.h to be included, which destrois the auto-gen system...
#if CSR_BT_BT_VERSION < CSR_BT_BLUETOOTH_VERSION_3P0
#define CSR_BT_EXCLUDE_HCI_READ_ENCRYPTION_KEY_SIZE 
#define CSR_BT_EXCLUDE_SM_IO_CAPABILITY_REQUEST
#define CSR_BT_EXCLUDE_SM_IO_CAPABILITY_REQUEST_NEG
#define CSR_BT_EXCLUDE_SM_SEND_KEYPRESS_NOTIFICATION
#define CSR_BT_EXCLUDE_SM_USER_CONFIRMATION_REQUEST
#define CSR_BT_EXCLUDE_SM_USER_CONFIRMATION_REQUEST_NEG
#define CSR_BT_EXCLUDE_SM_USER_PASSKEY_REQUEST
#define CSR_BT_EXCLUDE_SM_USER_PASSKEY_REQUEST_NEG
#endif
*/
#ifndef CSR_BT_INSTALL_CM_READ_FAILED_CONTACT_COUNTER
#define CSR_BT_EXCLUDE_HCI_READ_FAILED_CONTACT_COUNT
#endif

#ifndef CSR_BT_INSTALL_CM_READ_LOCAL_EXT_FEATURES
#define CSR_BT_EXCLUDE_HCI_READ_LOCAL_EXT_FEATURES
#endif

#ifndef CSR_BT_INSTALL_CM_READ_RSSI
#define CSR_BT_EXCLUDE_HCI_READ_RSSI
#endif

#ifndef CSR_BT_INSTALL_CM_READ_SCAN_EANBLE
#define CSR_BT_EXCLUDE_HCI_READ_SCAN_ENABLE
#endif

#ifndef CSR_BT_INSTALL_CM_READ_TX_POWER_LEVEL
#define CSR_BT_EXCLUDE_HCI_READ_TX_POWER_LEVEL
#endif

#ifndef CSR_BT_INSTALL_L2CAP_MODULE
#define CSR_BT_EXCLUDE_HCI_WRITE_AUTO_FLUSH_TIMEOUT
#endif

#ifndef CSR_BT_INSTALL_CM_SWITCH_ROLE_PUBLIC
#define CSR_BT_EXCLUDE_LP_WRITE_ALWAYS_MASTER_DEVICES
#endif

#ifndef CSR_BT_INSTALL_SC_AUTHENTICATE
#define CSR_BT_EXCLUDE_SM_AUTHENTICATE
#endif

#ifndef CSR_BT_INSTALL_SC_ENCRYPTION
#define CSR_BT_EXCLUDE_SM_ENCRYPT
#endif

/* Unused DM lib functions - Typically located in dm_hci_int_cc_gen.c and lib-finctions*/
#define CSR_BT_EXCLUDE_HCI_CHANGE_ACL_CONN_PKT_TYPE
#define CSR_BT_EXCLUDE_HCI_EXIT_PERIODIC_INQUIRY_MODE
#define CSR_BT_EXCLUDE_HCI_FLUSH
#define CSR_BT_EXCLUDE_HCI_PERIODIC_INQUIRY_MODE
#define CSR_BT_EXCLUDE_HCI_READ_AUTH_ENABLE
#define CSR_BT_EXCLUDE_HCI_READ_AUTO_FLUSH_TIMEOUT
#define CSR_BT_EXCLUDE_HCI_READ_COUNTRY_CODE
#define CSR_BT_EXCLUDE_HCI_READ_DEFAULT_LINK_POLICY_SETTINGS
#define CSR_BT_EXCLUDE_HCI_READ_ENC_MODE
#define CSR_BT_EXCLUDE_HCI_READ_HOLD_MODE_ACTIVITY
#define CSR_BT_EXCLUDE_HCI_READ_INQUIRY_MODE
#define CSR_BT_EXCLUDE_HCI_READ_INQUIRY_RESPONSE_TX_POWER_LEVEL
#define CSR_BT_EXCLUDE_HCI_READ_INQUIRY_SCAN_TYPE
#define CSR_BT_EXCLUDE_HCI_READ_INQUIRYSCAN_ACTIVITY
#define CSR_BT_EXCLUDE_HCI_READ_LINK_SUPERV_TIMEOUT
#define CSR_BT_EXCLUDE_HCI_READ_LMP_HANDLE
#define CSR_BT_EXCLUDE_HCI_READ_NUM_BCAST_RETXS
#define CSR_BT_EXCLUDE_HCI_READ_PAGESCAN_ACTIVITY
#define CSR_BT_EXCLUDE_HCI_READ_PAGESCAN_MODE
#define CSR_BT_EXCLUDE_HCI_READ_PAGESCAN_PERIOD_MODE
#define CSR_BT_EXCLUDE_HCI_READ_PIN_TYPE
#define CSR_BT_EXCLUDE_HCI_READ_SCO_FLOW_CON_ENABLE
#define CSR_BT_EXCLUDE_HCI_READ_STORED_LINK_KEY
#define CSR_BT_EXCLUDE_HCI_READ_VOICE_SETTING
#define CSR_BT_EXCLUDE_HCI_RESET_FAILED_CONTACT_COUNT
#ifndef CSR_TARGET_PRODUCT_WEARABLE
#define CSR_BT_EXCLUDE_HCI_READ_CONN_ACCEPT_TIMEOUT 
#define CSR_BT_EXCLUDE_HCI_WRITE_CONN_ACCEPT_TIMEOUT 
#endif /* CSR_TARGET_PRODUCT_WEARABLE */
#define CSR_BT_EXCLUDE_HCI_WRITE_HOLD_MODE_ACTIVITY
#define CSR_BT_EXCLUDE_HCI_WRITE_NUM_BCAST_RETXS
#define CSR_BT_EXCLUDE_HCI_WRITE_PAGESCAN_MODE
#define CSR_BT_EXCLUDE_HCI_WRITE_PAGESCAN_PERIOD_MODE
#define CSR_BT_EXCLUDE_HCI_WRITE_PIN_TYPE
#define CSR_BT_EXCLUDE_HCI_WRITE_SCO_FLOW_CON_ENABLE
#define CSR_BT_EXCLUDE_HCI_WRITE_STORED_LINK_KEY
#define CSR_BT_EXCLUDE_HCI_READ_LINK_POLICY_SETTINGS
#define CSR_BT_EXCLUDE_HCI_READ_PAGE_SCAN_TYPE
#define CSR_BT_EXCLUDE_HCI_READ_PAGE_TIMEOUT
#define CSR_BT_EXCLUDE_HCI_SET_EVENT_MASK /* lib-function never reffered, but HCI-command used in core-stack */
#define CSR_BT_EXCLUDE_SM_DATA_SIGN 
#define CSR_BT_EXCLUDE_SM_GENERATE_NONRESOLVABLE_PRIVATE_ADDRESS
#define CSR_BT_EXCLUDE_SM_READ_DEVICE

#ifdef CSR_BT_INSTALL_CHANGE_ACL_PACKET_TYPE
#undef CSR_BT_EXCLUDE_HCI_CHANGE_ACL_CONN_PKT_TYPE
#endif


#define DM_BT_VERSION BT_VERSION_5p4

#if defined(CSR_TARGET_PRODUCT_WEARABLE)
/* Start of WEARABLE Specific configurations */

#undef INSTALL_DM_POWERSTATES_MODULE

#undef BUILD_FOR_HOST_FOR_ENCRYPTION_ATT_RACE
#undef INSTALL_DLE
#define EXCLUDE_CSR_BT_ASM_MODULE
#define CSR_BT_GATT_EXCLUDE_MANDATORY_DB_REGISTRATION
#define EXCLUDE_GATT_GAP_ENCRYPTED_DATA_KEY_MATERIAL
#undef CSR_BT_GATT_CACHING

#define CSR_BT_GATT_INSTALL_CLIENT_SERVICE_REGISTRATION

#ifdef RFCOMM_MULTI_THREAD
#undef RFCOMM_MULTI_THREAD
#endif

#ifndef ATT_GLOBAL_STATE
#define ATT_GLOBAL_STATE 
#endif

#ifdef INSTALL_ATT_BREDR
#undef INSTALL_ATT_BREDR
#endif

/* By default have log enabled for wearables */
#define CSR_LOG_ENABLE

#define CSR_BT_GLOBAL_INSTANCE
#define EXCLUDE_DM_SM_SIRK_OPERATION_REQ

#define INSTALL_2LE

#ifndef INSTALL_L2CAP_LECOC_CB
#define INSTALL_L2CAP_LECOC_CB
#endif 

#define INSTALL_L2CAP_LECOC_TX_SEG


#define CSR_BT_GATT_MSG_RETRY_TIMER_VALUE                   (10) /* In ms */
#define CSR_BT_INSTALL_GATT_CONGESTION_INDICATION_SUPPORT

/* Following feature optimizes number of PS accesses done by different PS APIs.*/
#define TD_DB_INSTALL_OPTIMIZED_PS_ACCESS

#ifdef CSR_BT_GATT_INSTALL_FLAT_DB
#undef CSR_BT_GATT_INSTALL_FLAT_DB
#endif


#if defined (CSR_PLATFORM_WINDOWS) || defined (CSR_PLATFORM_LINUX)
#define CSR_TARGET_PRODUCT_WEARABLE_X86
#else
#define CSR_TARGET_PRODUCT_WEARABLE_PLATFORM
#endif

#define BMM_SOCK_MAX_RFCOMM_CONN                    2
#define BMM_SOCK_MAX_LECOC_CONN                     2

#define BMM_SOCK_MAX_RFCOMM_FRAME_SIZE              990
#define BMM_SOCK_MAX_LECOC_MTU                      1974

/* Read, Write without response, Write, Notify, Indicate */
#define GATT_OFFLOAD_CLIENT_PROPERTIES  0x3E
/* Read, Write without response, Write, Notify, Indicate */
#define GATT_OFFLOAD_SERVER_PROPERTIES  0x3E

#define INCLUDE_HCI_ARBITER

/* #define SYN_DEBUG_LOGS_BUFFER_ENABLE */

#ifndef GATT_OFFLOAD
#define GATT_OFFLOAD
#define GATT_SEQUENCING
#endif

#define MS_EXT_ADV_MAX_ADV_HANDLES 2
#define MS_EXT_SCAN_MAX_SCANNERS 3

/* End of WEARABLE configuration */
#endif 

#define L2CAP_HCI_DATA_CREDIT_SLOW_CHECKS


#define BLUESTACK_SAFE_FUNCTIONS_AVAILABLE
#define qbl_memscpy SynMemCpyS
#define qbl_memsmove SynMemMoveS


#ifdef __cplusplus
}
#endif


#endif
