/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "gatt_offload_mgr.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Uuid, Uuid, AUTO)


PB_BIND(GattCharacteristic, GattCharacteristic, AUTO)


PB_BIND(EndpointId, EndpointId, AUTO)


PB_BIND(GattCapabilities, GattCapabilities, AUTO)


PB_BIND(gatt_register_service, gatt_register_service, AUTO)


PB_BIND(gatt_unregister_service, gatt_unregister_service, AUTO)


PB_BIND(gatt_clear_services, gatt_clear_services, AUTO)


PB_BIND(gatt_register_service_complete, gatt_register_service_complete, AUTO)


PB_BIND(gatt_unregister_service_complete, gatt_unregister_service_complete, AUTO)


PB_BIND(gatt_clear_services_complete, gatt_clear_services_complete, AUTO)


PB_BIND(gatt_error_report, gatt_error_report, AUTO)


PB_BIND(gatt_get_capabilities_rsp, gatt_get_capabilities_rsp, AUTO)






