/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_GATT_OFFLOAD_MGR_PB_H_INCLUDED
#define PB_GATT_OFFLOAD_MGR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Role {
    Role_SERVER = 0,
    Role_CLIENT = 1
} Role;

typedef enum _GattError {
    GattError_UNKNOWN = 0,
    GattError_DATABASE_OUT_OF_SYNC = 1,
    GattError_RESPONSE_TIMEOUT = 2,
    GattError_PROTOCOL_VIOLATION = 3
} GattError;

typedef enum _GattStatus {
    GattStatus_SUCCESS = 0,
    GattStatus_INVALID_ENDPOINT_ID = 1,
    GattStatus_UNSUPPORTED_ROLE = 2,
    GattStatus_INSUFFICIENT_RESOURCES = 3,
    GattStatus_INTERNAL_ERROR = 4
} GattStatus;

/* Struct definitions */
typedef struct _Uuid {
    pb_callback_t uuid;
} Uuid;

typedef struct _GattCharacteristic {
    Uuid uuid;
    int32_t properties;
    int32_t valueHandle;
} GattCharacteristic;

typedef struct _EndpointId {
    uint64_t hubID; /* 0 for Q6-LPASS */
    uint64_t endpointID; /* Hardcoded, 0-server, 1-client , for all profiles rfcomm/gat/lecoc */
} EndpointId;

typedef struct _GattCapabilities {
    int32_t suppGattClientProperties;
    int32_t suppGattServerProperties;
} GattCapabilities;

typedef struct _gatt_register_service {
    int32_t sessionId;
    int32_t aclConnectionHandle;
    int32_t attMtu;
    Role role;
    Uuid uuid;
    pb_callback_t gattCharacteristic;
    EndpointId endpointId;
} gatt_register_service;

/* API to unoffload the GATT service to the endpoint for GATT client or server. */
typedef struct _gatt_unregister_service {
    int32_t sessionId;
} gatt_unregister_service;

/* API to clear offloaded service either in client role or server role. */
typedef struct _gatt_clear_services {
    int32_t aclConnectionHandle;
} gatt_clear_services;

typedef struct _gatt_register_service_complete {
    int32_t sessionId;
    GattStatus status;
} gatt_register_service_complete;

typedef struct _gatt_unregister_service_complete {
    int32_t sessionId;
} gatt_unregister_service_complete;

typedef struct _gatt_clear_services_complete {
    int32_t aclConnectionHandle;
} gatt_clear_services_complete;

typedef struct _gatt_error_report {
    int32_t aclConnectionHandle;
    int32_t localCid;
    GattError error;
} gatt_error_report;

typedef struct _gatt_get_capabilities_rsp {
    GattCapabilities capabilities;
} gatt_get_capabilities_rsp;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Role_MIN Role_SERVER
#define _Role_MAX Role_CLIENT
#define _Role_ARRAYSIZE ((Role)(Role_CLIENT+1))

#define _GattError_MIN GattError_UNKNOWN
#define _GattError_MAX GattError_PROTOCOL_VIOLATION
#define _GattError_ARRAYSIZE ((GattError)(GattError_PROTOCOL_VIOLATION+1))

#define _GattStatus_MIN GattStatus_SUCCESS
#define _GattStatus_MAX GattStatus_INTERNAL_ERROR
#define _GattStatus_ARRAYSIZE ((GattStatus)(GattStatus_INTERNAL_ERROR+1))





#define gatt_register_service_role_ENUMTYPE Role



#define gatt_register_service_complete_status_ENUMTYPE GattStatus



#define gatt_error_report_error_ENUMTYPE GattError



/* Initializer values for message structs */
#define Uuid_init_default                        {{{NULL}, NULL}}
#define GattCharacteristic_init_default          {Uuid_init_default, 0, 0}
#define EndpointId_init_default                  {0, 0}
#define GattCapabilities_init_default            {0, 0}
#define gatt_register_service_init_default       {0, 0, 0, _Role_MIN, Uuid_init_default, {{NULL}, NULL}, EndpointId_init_default}
#define gatt_unregister_service_init_default     {0}
#define gatt_clear_services_init_default         {0}
#define gatt_register_service_complete_init_default {0, _GattStatus_MIN}
#define gatt_unregister_service_complete_init_default {0}
#define gatt_clear_services_complete_init_default {0}
#define gatt_error_report_init_default           {0, 0, _GattError_MIN}
#define gatt_get_capabilities_rsp_init_default   {GattCapabilities_init_default}
#define Uuid_init_zero                           {{{NULL}, NULL}}
#define GattCharacteristic_init_zero             {Uuid_init_zero, 0, 0}
#define EndpointId_init_zero                     {0, 0}
#define GattCapabilities_init_zero               {0, 0}
#define gatt_register_service_init_zero          {0, 0, 0, _Role_MIN, Uuid_init_zero, {{NULL}, NULL}, EndpointId_init_zero}
#define gatt_unregister_service_init_zero        {0}
#define gatt_clear_services_init_zero            {0}
#define gatt_register_service_complete_init_zero {0, _GattStatus_MIN}
#define gatt_unregister_service_complete_init_zero {0}
#define gatt_clear_services_complete_init_zero   {0}
#define gatt_error_report_init_zero              {0, 0, _GattError_MIN}
#define gatt_get_capabilities_rsp_init_zero      {GattCapabilities_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Uuid_uuid_tag                            1
#define GattCharacteristic_uuid_tag              1
#define GattCharacteristic_properties_tag        2
#define GattCharacteristic_valueHandle_tag       3
#define EndpointId_hubID_tag                     1
#define EndpointId_endpointID_tag                2
#define GattCapabilities_suppGattClientProperties_tag 1
#define GattCapabilities_suppGattServerProperties_tag 2
#define gatt_register_service_sessionId_tag      1
#define gatt_register_service_aclConnectionHandle_tag 2
#define gatt_register_service_attMtu_tag         3
#define gatt_register_service_role_tag           4
#define gatt_register_service_uuid_tag           5
#define gatt_register_service_gattCharacteristic_tag 6
#define gatt_register_service_endpointId_tag     7
#define gatt_unregister_service_sessionId_tag    1
#define gatt_clear_services_aclConnectionHandle_tag 1
#define gatt_register_service_complete_sessionId_tag 1
#define gatt_register_service_complete_status_tag 2
#define gatt_unregister_service_complete_sessionId_tag 1
#define gatt_clear_services_complete_aclConnectionHandle_tag 1
#define gatt_error_report_aclConnectionHandle_tag 1
#define gatt_error_report_localCid_tag           2
#define gatt_error_report_error_tag              3
#define gatt_get_capabilities_rsp_capabilities_tag 1

/* Struct field encoding specification for nanopb */
#define Uuid_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    uuid,              1)
#define Uuid_CALLBACK pb_default_field_callback
#define Uuid_DEFAULT NULL

#define GattCharacteristic_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  uuid,              1) \
X(a, STATIC,   REQUIRED, INT32,    properties,        2) \
X(a, STATIC,   REQUIRED, INT32,    valueHandle,       3)
#define GattCharacteristic_CALLBACK NULL
#define GattCharacteristic_DEFAULT NULL
#define GattCharacteristic_uuid_MSGTYPE Uuid

#define EndpointId_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   hubID,             1) \
X(a, STATIC,   REQUIRED, UINT64,   endpointID,        2)
#define EndpointId_CALLBACK NULL
#define EndpointId_DEFAULT NULL

#define GattCapabilities_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    suppGattClientProperties,   1) \
X(a, STATIC,   REQUIRED, INT32,    suppGattServerProperties,   2)
#define GattCapabilities_CALLBACK NULL
#define GattCapabilities_DEFAULT NULL

#define gatt_register_service_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    sessionId,         1) \
X(a, STATIC,   REQUIRED, INT32,    aclConnectionHandle,   2) \
X(a, STATIC,   REQUIRED, INT32,    attMtu,            3) \
X(a, STATIC,   REQUIRED, UENUM,    role,              4) \
X(a, STATIC,   REQUIRED, MESSAGE,  uuid,              5) \
X(a, CALLBACK, REPEATED, MESSAGE,  gattCharacteristic,   6) \
X(a, STATIC,   REQUIRED, MESSAGE,  endpointId,        7)
#define gatt_register_service_CALLBACK pb_default_field_callback
#define gatt_register_service_DEFAULT NULL
#define gatt_register_service_uuid_MSGTYPE Uuid
#define gatt_register_service_gattCharacteristic_MSGTYPE GattCharacteristic
#define gatt_register_service_endpointId_MSGTYPE EndpointId

#define gatt_unregister_service_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    sessionId,         1)
#define gatt_unregister_service_CALLBACK NULL
#define gatt_unregister_service_DEFAULT NULL

#define gatt_clear_services_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    aclConnectionHandle,   1)
#define gatt_clear_services_CALLBACK NULL
#define gatt_clear_services_DEFAULT NULL

#define gatt_register_service_complete_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    sessionId,         1) \
X(a, STATIC,   REQUIRED, UENUM,    status,            2)
#define gatt_register_service_complete_CALLBACK NULL
#define gatt_register_service_complete_DEFAULT NULL

#define gatt_unregister_service_complete_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    sessionId,         1)
#define gatt_unregister_service_complete_CALLBACK NULL
#define gatt_unregister_service_complete_DEFAULT NULL

#define gatt_clear_services_complete_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    aclConnectionHandle,   1)
#define gatt_clear_services_complete_CALLBACK NULL
#define gatt_clear_services_complete_DEFAULT NULL

#define gatt_error_report_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    aclConnectionHandle,   1) \
X(a, STATIC,   REQUIRED, INT32,    localCid,          2) \
X(a, STATIC,   REQUIRED, UENUM,    error,             3)
#define gatt_error_report_CALLBACK NULL
#define gatt_error_report_DEFAULT NULL

#define gatt_get_capabilities_rsp_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  capabilities,      1)
#define gatt_get_capabilities_rsp_CALLBACK NULL
#define gatt_get_capabilities_rsp_DEFAULT NULL
#define gatt_get_capabilities_rsp_capabilities_MSGTYPE GattCapabilities

extern const pb_msgdesc_t Uuid_msg;
extern const pb_msgdesc_t GattCharacteristic_msg;
extern const pb_msgdesc_t EndpointId_msg;
extern const pb_msgdesc_t GattCapabilities_msg;
extern const pb_msgdesc_t gatt_register_service_msg;
extern const pb_msgdesc_t gatt_unregister_service_msg;
extern const pb_msgdesc_t gatt_clear_services_msg;
extern const pb_msgdesc_t gatt_register_service_complete_msg;
extern const pb_msgdesc_t gatt_unregister_service_complete_msg;
extern const pb_msgdesc_t gatt_clear_services_complete_msg;
extern const pb_msgdesc_t gatt_error_report_msg;
extern const pb_msgdesc_t gatt_get_capabilities_rsp_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Uuid_fields &Uuid_msg
#define GattCharacteristic_fields &GattCharacteristic_msg
#define EndpointId_fields &EndpointId_msg
#define GattCapabilities_fields &GattCapabilities_msg
#define gatt_register_service_fields &gatt_register_service_msg
#define gatt_unregister_service_fields &gatt_unregister_service_msg
#define gatt_clear_services_fields &gatt_clear_services_msg
#define gatt_register_service_complete_fields &gatt_register_service_complete_msg
#define gatt_unregister_service_complete_fields &gatt_unregister_service_complete_msg
#define gatt_clear_services_complete_fields &gatt_clear_services_complete_msg
#define gatt_error_report_fields &gatt_error_report_msg
#define gatt_get_capabilities_rsp_fields &gatt_get_capabilities_rsp_msg

/* Maximum encoded size of messages (where known) */
/* Uuid_size depends on runtime parameters */
/* GattCharacteristic_size depends on runtime parameters */
/* gatt_register_service_size depends on runtime parameters */
#define EndpointId_size                          22
#define GATT_OFFLOAD_MGR_PB_H_MAX_SIZE           gatt_error_report_size
#define GattCapabilities_size                    22
#define gatt_clear_services_complete_size        11
#define gatt_clear_services_size                 11
#define gatt_error_report_size                   24
#define gatt_get_capabilities_rsp_size           24
#define gatt_register_service_complete_size      13
#define gatt_unregister_service_complete_size    11
#define gatt_unregister_service_size             11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
