/* SPDX-License-Identifier: Apache-2.0 */

#include <linker/common-rom-kernel-devices-aligned.ld>

#include <zephyr/linker/common-rom/common-rom-ztest.ld>

#include <zephyr/linker/common-rom/common-rom-init.ld>

#include <zephyr/linker/common-rom/common-rom-net.ld>

#include <zephyr/linker/common-rom/common-rom-bt.ld>

#include <zephyr/linker/common-rom/common-rom-logging.ld>

#include <zephyr/linker/common-rom/common-rom-debug.ld>

#include <linker/common-rom-interrupt-controllers-aligned.ld>

#include <zephyr/linker/common-rom/common-rom-misc.ld>
