#Common sw configurations
CONFIG_PDTSW_COMMON_MODULES_ENABLE=y
CONFIG_PDTSW_COMMON_STATE_MACHINE_ENABLE=y
CONFIG_PDTSW_COMMON_HEAP_MGR_ENABLE=y
CONFIG_PDTSW_COMMON_WORKER_THREAD_ENABLE=y
CONFIG_PDTSW_COMMON_GLINK_HEAP_SIZE=4096
CONFIG_PDTSW_COMMON_HEAP_SIZE=3072
#CONFIG_PDTSW_COMMON_UTILS_ENABLE=y
#CONFIG_PDTSW_COMMON_UTILS_DBG_LOGGING=y

# RSB
CONFIG_PDTSW_RSB_SERVICE_ENABLE=y
CONFIG_PDTSW_RSB_SERVICE_MAX_NUM_DATA_CLIENTS=3
CONFIG_PDTSW_RSB_SERVICE_MAX_NUM_STATUS_CLIENTS=2
CONFIG_PDTSW_RSB_SERVICE_HEAP_SIZE=1024
CONFIG_PDTSW_RSB_WORKQ_THREAD_PRIORITY=22
CONFIG_PDTSW_RSB_WORKQ_THREAD_STACK_SIZE=1536
#CONFIG_PDTSW_RSB_SERVICE_DBG_LOGGING=y
CONFIG_PDTSW_RSB_SERVICE_TEST=y

#Audio service configurations
CONFIG_PDTSW_AUDIO_SERVICE_ENABLE=y
CONFIG_PDTSW_AUDIO_SERVICE_ENABLE_PROFILING=n
CONFIG_PDTSW_AUDIO_SERVICE_ENABLE_LOG_LEVEL=0
CONFIG_PDTSW_AUDIO_SERVICE_TEST=y
CONFIG_QC_PDTSW_STHAL_ENABLE=y
CONFIG_QC_PDTSW_AUDIO_SVA_TEST=y
CONFIG_PDTSW_OFFLOAD_MGR_AUDIO_ENABLE=y

#Haptics service configurations
CONFIG_PDTSW_HAPTICS_SERVICE_ENABLE=y
CONFIG_PDTSW_HAPTICS_SERVICE_ENABLE_PROFILING=n
CONFIG_PDTSW_HAPTICS_SERVICE_ENABLE_LOG_LEVEL=0
CONFIG_PDTSW_HAPTICS_SERVICE_TEST=y
CONFIG_PDTSW_OFFLOAD_MGR_HAPTICS_ENABLE=y

# Offload manager
CONFIG_PDTSW_OFFLOAD_MGR_ENABLE=y
CONFIG_PDTSW_OFFLOAD_MGR_RSB_ENABLE=y
CONFIG_QC_PDTSW_OFFLOAD_MGR_THREAD_PRIORITY=21
CONFIG_QC_PDTSW_OFFLOAD_MGR_THREAD_STACK_SIZE=1536

#CONFIG_SERIAL=y
#CONFIG_QC_UART=y

#CONFIG_LOG=y
#CONFIG_LOG_MODE_MINIMAL=n
#CONFIG_LOG_MODE_DEFERRED=y
#CONFIG_LOG_PRINTK=y

#CONFIG_SHELL=y
#CONFIG_SHELL_BACKENDS=y
#CONFIG_SHELL_ASYNC_API=y
#CONFIG_SHELL_BACKEND_SERIAL_ASYNC_RX_BUFFER_SIZE=32

#CONFIG_SHELL_MINIMAL=y
#CONFIG_SHELL_CMDS=y
#CONFIG_SHELL_TAB=y
#CONFIG_SHELL_TAB_AUTOCOMPLETION=y
#CONFIG_SHELL_HELP=y
#CONFIG_SHELL_VT100_COMMANDS=y
#CONFIG_SHELL_VT100_COLORS=y

# Glink Shell Flags
CONFIG_GLINK_SHELL=y
CONFIG_GLINK_SHELL_PASSTHROUGH=y
CONFIG_GLINK_SHELL_THREAD_PRIORITY=120
CONFIG_GLINK_SHELL_THREAD_STACK_SZ=1536
CONFIG_GLINK_SHELL_LOG_LEVEL=2
CONFIG_GLINK_SHELL_MSGQ_ELEM_COUNT=20
CONFIG_GLINK_SHELL_TRANSPORT_BUF_SZ=256

# Battery service
CONFIG_PDTSW_BATTERY_SERVICE_ENABLE=y
CONFIG_PDTSW_BATTERY_SERVICE_TEST=y

CONFIG_NANOPB=y
CONFIG_PDTSW_QSH_GLINK_ROUTER_ENABLE=y
CONFIG_PDTSW_QSH_GLINK_ROUTER_HEAP_SIZE=1024
CONFIG_PDTSW_QSH_DISPLAY_BRIDGE_ENABLE=y
CONFIG_PDTSW_QSH_DISPLAY_BRIDGE_HEAP_SIZE=1536
CONFIG_PDTSW_QSH_GLINK_ROUTER_TEST=n
CONFIG_PDTSW_QSH_DISPLAY_BRIDGE_TEST=y

# PSRAM Arbiter
CONFIG_QC_PDTSW_PSRAM_ARBITER_ENABLE=y
CONFIG_QC_PDTSW_PSRAM_ARBITER_LOG_LEVEL=3
CONFIG_QC_PDTSW_UTILITY_GLINK_LOG_LEVEL=3

# Debug Services
CONFIG_QC_SHIM_DIAG=y
CONFIG_QC_TRACER_TEST=n
CONFIG_PDTSW_DEBUG_SERVICE_HEAP_SIZE=1536
CONFIG_QC_SHIM_DIAG_MASK_EX_HEAP_SZ=1024

CONFIG_QC_DIAG_SUPPORT_QSR4=y
CONFIG_MSG_V4_SSID_AAM_TABLE_ENTRY=1500

CONFIG_QC_BUFFERED_LOGGING=n
CONFIG_QC_BUFFERED_LOGGING_BUF_SZ=4096
CONFIG_QC_BUFFERED_LOGGING_FLUSH_THRESHOLD=3276

CONFIG_QC_BUFFERED_LOGGING_DEBUG=n
CONFIG_QC_BUFFERED_LOGGING_DEBUG_LOG=n
CONFIG_QC_BUFFERED_LOGGING_DEBUG_KPI_TEST=n