# PSRAM
CONFIG_QC_PDTSW_PSRAM_TEST_SWM=n

# PSRAM Arbiter Client
CONFIG_PDTSW_COMMON_MODULES_ENABLE=y
CONFIG_PDTSW_COMMON_HEAP_MGR_ENABLE=y
CONFIG_PDTSW_COMMON_WORKER_THREAD_ENABLE=y
CONFIG_PDTSW_COMMON_HEAP_SIZE=3072

CONFIG_QC_PDTSW_PSRAM_CLIENT_ENABLE=y
CONFIG_QC_PDTSW_PSRAM_CLIENT_MAX_LOCAL_CLIENTS=3
CONFIG_QC_PDTSW_PSRAM_CLIENT_MAX_BUFF_REQ=5
CONFIG_QC_PDTSW_PSRAM_CLIENT_LOG_LEVEL=0
CONFIG_QC_PDTSW_UTILITY_GLINK_LOG_LEVEL=0
CONFIG_QC_PDTSW_PSRAM_CLIENT_TEST=n

#CONFIG_SHELL=y
#CONFIG_SHELL_ASYNC_API=y
#CONFIG_SHELL_BACKENDS=n

#CONFIG_LOG=y
#CONFIG_LOG_MODE_MINIMAL=n
#CONFIG_LOG_MODE_DEFERRED=y
#CONFIG_LOG_PRINTK=y

# # Glink Shell
#CONFIG_GLINK_SHELL=y
#CONFIG_GLINK_SHELL_PASSTHROUGH=n
#CONFIG_GLINK_SHELL_THREAD_PRIORITY=120
#CONFIG_GLINK_SHELL_THREAD_STACK_SZ=1536
#CONFIG_GLINK_SHELL_LOG_LEVEL=2
#CONFIG_GLINK_SHELL_MSGQ_ELEM_COUNT=20
#CONFIG_GLINK_SHELL_PROMPT="wmshell~$ "
#CONFIG_GLINK_SHELL_TRANSPORT_BUF_SZ=512

# Debug Services
CONFIG_QC_DIAG=y
CONFIG_QC_UTILS=y
CONFIG_QC_DIAG_TRACER_PASSTHRU=y
CONFIG_QC_TRACER_TEST=y
CONFIG_PDTSW_DEBUG_SERVICE_HEAP_SIZE=15360
CONFIG_QC_DIAG_SUPPORT_QSR4=y
CONFIG_QC_SHIM_DIAG_MASK_EX_HEAP_SZ=1024
# Shim Diag Proxy Service
CONFIG_QC_DIAG_SHIM_DIAG_CONTROL_PROXY=y
CONFIG_MSG_V4_SSID_AAM_TABLE_ENTRY=8192
CONFIG_QC_TEST_ISLAND_ENTRY_EXIT_TRACER=n
