/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "socket_mgr.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_offload_proto_EndpointId, google_offload_proto_EndpointId, AUTO)


PB_BIND(google_offload_proto_LECOCChannelInfo, google_offload_proto_LECOCChannelInfo, AUTO)


PB_BIND(google_offload_proto_RFCOMMChannelInfo, google_offload_proto_RFCOMMChannelInfo, AUTO)


PB_BIND(google_offload_proto_ChannelInfo, google_offload_proto_ChannelInfo, AUTO)


PB_BIND(google_offload_proto_SocketContext, google_offload_proto_SocketContext, AUTO)


PB_BIND(google_offload_proto_socket_open, google_offload_proto_socket_open, AUTO)


PB_BIND(google_offload_proto_socket_close, google_offload_proto_socket_close, AUTO)


PB_BIND(google_offload_proto_socket_close_ind, google_offload_proto_socket_close_ind, AUTO)


PB_BIND(google_offload_proto_socket_open_rsp, google_offload_proto_socket_open_rsp, AUTO)


PB_BIND(google_offload_proto_socket_close_rsp, google_offload_proto_socket_close_rsp, AUTO)


PB_BIND(google_offload_proto_LeCocCapabilities, google_offload_proto_LeCocCapabilities, AUTO)


PB_BIND(google_offload_proto_RfCommCapabilities, google_offload_proto_RfCommCapabilities, AUTO)


PB_BIND(google_offload_proto_SocketCapabilities, google_offload_proto_SocketCapabilities, AUTO)





