/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_GOOGLE_OFFLOAD_PROTO_SOCKET_SOCKET_MGR_PB_H_INCLUDED
#define PB_GOOGLE_OFFLOAD_PROTO_SOCKET_SOCKET_MGR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _google_offload_proto_Status {
    google_offload_proto_Status_OFFLOAD_STATUS_SUCCESS = 0,
    google_offload_proto_Status_OFFLOAD_STATUS_FAILURE = 1
} google_offload_proto_Status;

/* * Type of Socket ,BT profile used */
typedef enum _google_offload_proto_Protocol {
    google_offload_proto_Protocol_LE_COC = 0,
    google_offload_proto_Protocol_RFCOMM = 1
} google_offload_proto_Protocol;

/* Struct definitions */
typedef struct _google_offload_proto_EndpointId {
    uint64_t hubID; /* 0 for Q6-LPASS */
    uint64_t endpointID; /* Hardcoded, 0-server, 1-client , for all profiles rfcomm/gat/lecoc */
} google_offload_proto_EndpointId;

typedef struct _google_offload_proto_LECOCChannelInfo {
    uint32_t localCid;
    uint32_t remoteCid;
    uint32_t psm;
    uint32_t localMtu;
    uint32_t remoteMtu;
    uint32_t localMps;
    uint32_t remoteMps;
    uint32_t initialRxCredits;
    uint32_t initialTxCredits;
} google_offload_proto_LECOCChannelInfo;

typedef struct _google_offload_proto_RFCOMMChannelInfo {
    uint32_t localCid;
    uint32_t remoteCid;
    uint32_t localmtu;
    uint32_t remotemtu;
    uint32_t initialRxCredits; /* ZERO */
    uint32_t initialTxCredits;
    uint32_t dlci;
    uint32_t maxFrameSize;
    uint32_t muxInitiatorFlag;
} google_offload_proto_RFCOMMChannelInfo;

typedef struct _google_offload_proto_ChannelInfo {
    bool has_rfcomm_channel_info;
    google_offload_proto_RFCOMMChannelInfo rfcomm_channel_info;
    bool has_lecoc_channel_info;
    google_offload_proto_LECOCChannelInfo lecoc_channel_info;
} google_offload_proto_ChannelInfo;

typedef struct _google_offload_proto_SocketContext {
    uint64_t socket_id; /* will be random number, but unique from Android */
    pb_callback_t socket_name; /* ignore for now in code on LPASS */
    uint32_t aclConnectionHandle;
    google_offload_proto_Protocol type;
    google_offload_proto_ChannelInfo channel_info;
    google_offload_proto_EndpointId offloadEndpointId;
} google_offload_proto_SocketContext;

/* *
 API to notify the offload stack that the socket is opened.

 @param context Socket context including socket id, channel, hub, and endpoint * info */
typedef struct _google_offload_proto_socket_open {
    google_offload_proto_SocketContext ctx;
} google_offload_proto_socket_open;

/* *
 API to notify the offload stack that the socket is closed.

 @param socketId Identifier assigned to the socket by the host stack */
typedef struct _google_offload_proto_socket_close {
    uint64_t sock_id;
} google_offload_proto_socket_close;

typedef struct _google_offload_proto_socket_close_ind {
    uint64_t sock_id;
    int32_t reason;
} google_offload_proto_socket_close_ind;

/* *
 Invoked when IBluetoothSocket.opened() is successful.

 @param socketId Identifier assigned to the socket by the host stack */
typedef struct _google_offload_proto_socket_open_rsp {
    uint64_t sock_id;
    google_offload_proto_Status status; /* 0=success,1=fail */
    pb_callback_t reason;
} google_offload_proto_socket_open_rsp;

/* *
 Invoked when offload app or stack request host stack to close the socket, or
 when IBluetoothSocket.opened() fails. */
typedef struct _google_offload_proto_socket_close_rsp {
    uint64_t sock_id;
    pb_callback_t reason; /* Need to define this , mapping to fluroide */
} google_offload_proto_socket_close_rsp;

typedef struct _google_offload_proto_LeCocCapabilities {
    uint32_t numOfSocketSupported;
    uint32_t mtu;
} google_offload_proto_LeCocCapabilities;

typedef struct _google_offload_proto_RfCommCapabilities {
    uint32_t numOfSocketSupported;
    uint32_t maxFrameSize;
} google_offload_proto_RfCommCapabilities;

typedef struct _google_offload_proto_SocketCapabilities {
    google_offload_proto_LeCocCapabilities lecoc_capabilities;
    google_offload_proto_RfCommCapabilities rfcomm_capabilities;
} google_offload_proto_SocketCapabilities;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _google_offload_proto_Status_MIN google_offload_proto_Status_OFFLOAD_STATUS_SUCCESS
#define _google_offload_proto_Status_MAX google_offload_proto_Status_OFFLOAD_STATUS_FAILURE
#define _google_offload_proto_Status_ARRAYSIZE ((google_offload_proto_Status)(google_offload_proto_Status_OFFLOAD_STATUS_FAILURE+1))

#define _google_offload_proto_Protocol_MIN google_offload_proto_Protocol_LE_COC
#define _google_offload_proto_Protocol_MAX google_offload_proto_Protocol_RFCOMM
#define _google_offload_proto_Protocol_ARRAYSIZE ((google_offload_proto_Protocol)(google_offload_proto_Protocol_RFCOMM+1))





#define google_offload_proto_SocketContext_type_ENUMTYPE google_offload_proto_Protocol




#define google_offload_proto_socket_open_rsp_status_ENUMTYPE google_offload_proto_Status






/* Initializer values for message structs */
#define google_offload_proto_EndpointId_init_default {0, 0}
#define google_offload_proto_LECOCChannelInfo_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define google_offload_proto_RFCOMMChannelInfo_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define google_offload_proto_ChannelInfo_init_default {false, google_offload_proto_RFCOMMChannelInfo_init_default, false, google_offload_proto_LECOCChannelInfo_init_default}
#define google_offload_proto_SocketContext_init_default {0, {{NULL}, NULL}, 0, _google_offload_proto_Protocol_MIN, google_offload_proto_ChannelInfo_init_default, google_offload_proto_EndpointId_init_default}
#define google_offload_proto_socket_open_init_default {google_offload_proto_SocketContext_init_default}
#define google_offload_proto_socket_close_init_default {0}
#define google_offload_proto_socket_close_ind_init_default {0, 0}
#define google_offload_proto_socket_open_rsp_init_default {0, _google_offload_proto_Status_MIN, {{NULL}, NULL}}
#define google_offload_proto_socket_close_rsp_init_default {0, {{NULL}, NULL}}
#define google_offload_proto_LeCocCapabilities_init_default {0, 0}
#define google_offload_proto_RfCommCapabilities_init_default {0, 0}
#define google_offload_proto_SocketCapabilities_init_default {google_offload_proto_LeCocCapabilities_init_default, google_offload_proto_RfCommCapabilities_init_default}
#define google_offload_proto_EndpointId_init_zero {0, 0}
#define google_offload_proto_LECOCChannelInfo_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define google_offload_proto_RFCOMMChannelInfo_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define google_offload_proto_ChannelInfo_init_zero {false, google_offload_proto_RFCOMMChannelInfo_init_zero, false, google_offload_proto_LECOCChannelInfo_init_zero}
#define google_offload_proto_SocketContext_init_zero {0, {{NULL}, NULL}, 0, _google_offload_proto_Protocol_MIN, google_offload_proto_ChannelInfo_init_zero, google_offload_proto_EndpointId_init_zero}
#define google_offload_proto_socket_open_init_zero {google_offload_proto_SocketContext_init_zero}
#define google_offload_proto_socket_close_init_zero {0}
#define google_offload_proto_socket_close_ind_init_zero {0, 0}
#define google_offload_proto_socket_open_rsp_init_zero {0, _google_offload_proto_Status_MIN, {{NULL}, NULL}}
#define google_offload_proto_socket_close_rsp_init_zero {0, {{NULL}, NULL}}
#define google_offload_proto_LeCocCapabilities_init_zero {0, 0}
#define google_offload_proto_RfCommCapabilities_init_zero {0, 0}
#define google_offload_proto_SocketCapabilities_init_zero {google_offload_proto_LeCocCapabilities_init_zero, google_offload_proto_RfCommCapabilities_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define google_offload_proto_EndpointId_hubID_tag 1
#define google_offload_proto_EndpointId_endpointID_tag 2
#define google_offload_proto_LECOCChannelInfo_localCid_tag 1
#define google_offload_proto_LECOCChannelInfo_remoteCid_tag 2
#define google_offload_proto_LECOCChannelInfo_psm_tag 3
#define google_offload_proto_LECOCChannelInfo_localMtu_tag 4
#define google_offload_proto_LECOCChannelInfo_remoteMtu_tag 5
#define google_offload_proto_LECOCChannelInfo_localMps_tag 6
#define google_offload_proto_LECOCChannelInfo_remoteMps_tag 7
#define google_offload_proto_LECOCChannelInfo_initialRxCredits_tag 8
#define google_offload_proto_LECOCChannelInfo_initialTxCredits_tag 9
#define google_offload_proto_RFCOMMChannelInfo_localCid_tag 1
#define google_offload_proto_RFCOMMChannelInfo_remoteCid_tag 2
#define google_offload_proto_RFCOMMChannelInfo_localmtu_tag 3
#define google_offload_proto_RFCOMMChannelInfo_remotemtu_tag 4
#define google_offload_proto_RFCOMMChannelInfo_initialRxCredits_tag 5
#define google_offload_proto_RFCOMMChannelInfo_initialTxCredits_tag 6
#define google_offload_proto_RFCOMMChannelInfo_dlci_tag 7
#define google_offload_proto_RFCOMMChannelInfo_maxFrameSize_tag 8
#define google_offload_proto_RFCOMMChannelInfo_muxInitiatorFlag_tag 9
#define google_offload_proto_ChannelInfo_rfcomm_channel_info_tag 1
#define google_offload_proto_ChannelInfo_lecoc_channel_info_tag 2
#define google_offload_proto_SocketContext_socket_id_tag 1
#define google_offload_proto_SocketContext_socket_name_tag 2
#define google_offload_proto_SocketContext_aclConnectionHandle_tag 3
#define google_offload_proto_SocketContext_type_tag 4
#define google_offload_proto_SocketContext_channel_info_tag 5
#define google_offload_proto_SocketContext_offloadEndpointId_tag 6
#define google_offload_proto_socket_open_ctx_tag 1
#define google_offload_proto_socket_close_sock_id_tag 1
#define google_offload_proto_socket_close_ind_sock_id_tag 1
#define google_offload_proto_socket_close_ind_reason_tag 2
#define google_offload_proto_socket_open_rsp_sock_id_tag 1
#define google_offload_proto_socket_open_rsp_status_tag 2
#define google_offload_proto_socket_open_rsp_reason_tag 3
#define google_offload_proto_socket_close_rsp_sock_id_tag 1
#define google_offload_proto_socket_close_rsp_reason_tag 2
#define google_offload_proto_LeCocCapabilities_numOfSocketSupported_tag 1
#define google_offload_proto_LeCocCapabilities_mtu_tag 2
#define google_offload_proto_RfCommCapabilities_numOfSocketSupported_tag 1
#define google_offload_proto_RfCommCapabilities_maxFrameSize_tag 2
#define google_offload_proto_SocketCapabilities_lecoc_capabilities_tag 1
#define google_offload_proto_SocketCapabilities_rfcomm_capabilities_tag 2

/* Struct field encoding specification for nanopb */
#define google_offload_proto_EndpointId_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   hubID,             1) \
X(a, STATIC,   REQUIRED, UINT64,   endpointID,        2)
#define google_offload_proto_EndpointId_CALLBACK NULL
#define google_offload_proto_EndpointId_DEFAULT NULL

#define google_offload_proto_LECOCChannelInfo_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   localCid,          1) \
X(a, STATIC,   REQUIRED, UINT32,   remoteCid,         2) \
X(a, STATIC,   REQUIRED, UINT32,   psm,               3) \
X(a, STATIC,   REQUIRED, UINT32,   localMtu,          4) \
X(a, STATIC,   REQUIRED, UINT32,   remoteMtu,         5) \
X(a, STATIC,   REQUIRED, UINT32,   localMps,          6) \
X(a, STATIC,   REQUIRED, UINT32,   remoteMps,         7) \
X(a, STATIC,   REQUIRED, UINT32,   initialRxCredits,   8) \
X(a, STATIC,   REQUIRED, UINT32,   initialTxCredits,   9)
#define google_offload_proto_LECOCChannelInfo_CALLBACK NULL
#define google_offload_proto_LECOCChannelInfo_DEFAULT NULL

#define google_offload_proto_RFCOMMChannelInfo_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   localCid,          1) \
X(a, STATIC,   REQUIRED, UINT32,   remoteCid,         2) \
X(a, STATIC,   REQUIRED, UINT32,   localmtu,          3) \
X(a, STATIC,   REQUIRED, UINT32,   remotemtu,         4) \
X(a, STATIC,   REQUIRED, UINT32,   initialRxCredits,   5) \
X(a, STATIC,   REQUIRED, UINT32,   initialTxCredits,   6) \
X(a, STATIC,   REQUIRED, UINT32,   dlci,              7) \
X(a, STATIC,   REQUIRED, UINT32,   maxFrameSize,      8) \
X(a, STATIC,   REQUIRED, UINT32,   muxInitiatorFlag,   9)
#define google_offload_proto_RFCOMMChannelInfo_CALLBACK NULL
#define google_offload_proto_RFCOMMChannelInfo_DEFAULT NULL

#define google_offload_proto_ChannelInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rfcomm_channel_info,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lecoc_channel_info,   2)
#define google_offload_proto_ChannelInfo_CALLBACK NULL
#define google_offload_proto_ChannelInfo_DEFAULT NULL
#define google_offload_proto_ChannelInfo_rfcomm_channel_info_MSGTYPE google_offload_proto_RFCOMMChannelInfo
#define google_offload_proto_ChannelInfo_lecoc_channel_info_MSGTYPE google_offload_proto_LECOCChannelInfo

#define google_offload_proto_SocketContext_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   socket_id,         1) \
X(a, CALLBACK, REQUIRED, BYTES,    socket_name,       2) \
X(a, STATIC,   REQUIRED, UINT32,   aclConnectionHandle,   3) \
X(a, STATIC,   REQUIRED, UENUM,    type,              4) \
X(a, STATIC,   REQUIRED, MESSAGE,  channel_info,      5) \
X(a, STATIC,   REQUIRED, MESSAGE,  offloadEndpointId,   6)
#define google_offload_proto_SocketContext_CALLBACK pb_default_field_callback
#define google_offload_proto_SocketContext_DEFAULT NULL
#define google_offload_proto_SocketContext_channel_info_MSGTYPE google_offload_proto_ChannelInfo
#define google_offload_proto_SocketContext_offloadEndpointId_MSGTYPE google_offload_proto_EndpointId

#define google_offload_proto_socket_open_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  ctx,               1)
#define google_offload_proto_socket_open_CALLBACK NULL
#define google_offload_proto_socket_open_DEFAULT NULL
#define google_offload_proto_socket_open_ctx_MSGTYPE google_offload_proto_SocketContext

#define google_offload_proto_socket_close_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   sock_id,           1)
#define google_offload_proto_socket_close_CALLBACK NULL
#define google_offload_proto_socket_close_DEFAULT NULL

#define google_offload_proto_socket_close_ind_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   sock_id,           1) \
X(a, STATIC,   REQUIRED, INT32,    reason,            2)
#define google_offload_proto_socket_close_ind_CALLBACK NULL
#define google_offload_proto_socket_close_ind_DEFAULT NULL

#define google_offload_proto_socket_open_rsp_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   sock_id,           1) \
X(a, STATIC,   REQUIRED, UENUM,    status,            2) \
X(a, CALLBACK, REQUIRED, STRING,   reason,            3)
#define google_offload_proto_socket_open_rsp_CALLBACK pb_default_field_callback
#define google_offload_proto_socket_open_rsp_DEFAULT NULL

#define google_offload_proto_socket_close_rsp_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   sock_id,           1) \
X(a, CALLBACK, REQUIRED, STRING,   reason,            2)
#define google_offload_proto_socket_close_rsp_CALLBACK pb_default_field_callback
#define google_offload_proto_socket_close_rsp_DEFAULT NULL

#define google_offload_proto_LeCocCapabilities_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   numOfSocketSupported,   1) \
X(a, STATIC,   REQUIRED, UINT32,   mtu,               2)
#define google_offload_proto_LeCocCapabilities_CALLBACK NULL
#define google_offload_proto_LeCocCapabilities_DEFAULT NULL

#define google_offload_proto_RfCommCapabilities_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   numOfSocketSupported,   1) \
X(a, STATIC,   REQUIRED, UINT32,   maxFrameSize,      2)
#define google_offload_proto_RfCommCapabilities_CALLBACK NULL
#define google_offload_proto_RfCommCapabilities_DEFAULT NULL

#define google_offload_proto_SocketCapabilities_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  lecoc_capabilities,   1) \
X(a, STATIC,   REQUIRED, MESSAGE,  rfcomm_capabilities,   2)
#define google_offload_proto_SocketCapabilities_CALLBACK NULL
#define google_offload_proto_SocketCapabilities_DEFAULT NULL
#define google_offload_proto_SocketCapabilities_lecoc_capabilities_MSGTYPE google_offload_proto_LeCocCapabilities
#define google_offload_proto_SocketCapabilities_rfcomm_capabilities_MSGTYPE google_offload_proto_RfCommCapabilities

extern const pb_msgdesc_t google_offload_proto_EndpointId_msg;
extern const pb_msgdesc_t google_offload_proto_LECOCChannelInfo_msg;
extern const pb_msgdesc_t google_offload_proto_RFCOMMChannelInfo_msg;
extern const pb_msgdesc_t google_offload_proto_ChannelInfo_msg;
extern const pb_msgdesc_t google_offload_proto_SocketContext_msg;
extern const pb_msgdesc_t google_offload_proto_socket_open_msg;
extern const pb_msgdesc_t google_offload_proto_socket_close_msg;
extern const pb_msgdesc_t google_offload_proto_socket_close_ind_msg;
extern const pb_msgdesc_t google_offload_proto_socket_open_rsp_msg;
extern const pb_msgdesc_t google_offload_proto_socket_close_rsp_msg;
extern const pb_msgdesc_t google_offload_proto_LeCocCapabilities_msg;
extern const pb_msgdesc_t google_offload_proto_RfCommCapabilities_msg;
extern const pb_msgdesc_t google_offload_proto_SocketCapabilities_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define google_offload_proto_EndpointId_fields &google_offload_proto_EndpointId_msg
#define google_offload_proto_LECOCChannelInfo_fields &google_offload_proto_LECOCChannelInfo_msg
#define google_offload_proto_RFCOMMChannelInfo_fields &google_offload_proto_RFCOMMChannelInfo_msg
#define google_offload_proto_ChannelInfo_fields &google_offload_proto_ChannelInfo_msg
#define google_offload_proto_SocketContext_fields &google_offload_proto_SocketContext_msg
#define google_offload_proto_socket_open_fields &google_offload_proto_socket_open_msg
#define google_offload_proto_socket_close_fields &google_offload_proto_socket_close_msg
#define google_offload_proto_socket_close_ind_fields &google_offload_proto_socket_close_ind_msg
#define google_offload_proto_socket_open_rsp_fields &google_offload_proto_socket_open_rsp_msg
#define google_offload_proto_socket_close_rsp_fields &google_offload_proto_socket_close_rsp_msg
#define google_offload_proto_LeCocCapabilities_fields &google_offload_proto_LeCocCapabilities_msg
#define google_offload_proto_RfCommCapabilities_fields &google_offload_proto_RfCommCapabilities_msg
#define google_offload_proto_SocketCapabilities_fields &google_offload_proto_SocketCapabilities_msg

/* Maximum encoded size of messages (where known) */
/* google_offload_proto_SocketContext_size depends on runtime parameters */
/* google_offload_proto_socket_open_size depends on runtime parameters */
/* google_offload_proto_socket_open_rsp_size depends on runtime parameters */
/* google_offload_proto_socket_close_rsp_size depends on runtime parameters */
#define GOOGLE_OFFLOAD_PROTO_SOCKET_SOCKET_MGR_PB_H_MAX_SIZE google_offload_proto_ChannelInfo_size
#define google_offload_proto_ChannelInfo_size    112
#define google_offload_proto_EndpointId_size     22
#define google_offload_proto_LECOCChannelInfo_size 54
#define google_offload_proto_LeCocCapabilities_size 12
#define google_offload_proto_RFCOMMChannelInfo_size 54
#define google_offload_proto_RfCommCapabilities_size 12
#define google_offload_proto_SocketCapabilities_size 28
#define google_offload_proto_socket_close_ind_size 22
#define google_offload_proto_socket_close_size   11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
